/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.HourProfileDayPartId;


/**
 * HourProfileDayPartItem
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:24:13.221+01:00")
public class HourProfileDayPartItem   {
  @SerializedName("id")
  private HourProfileDayPartId id = null;

  @SerializedName("startHour")
  private String startHour = null;

  @SerializedName("endHour")
  private String endHour = null;

  @SerializedName("workedInHour")
  private String workedInHour = null;

  @SerializedName("workedInDay")
  private Double workedInDay = null;

  @SerializedName("dayPart")
  private Integer dayPart = null;

  public HourProfileDayPartItem id(HourProfileDayPartId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public HourProfileDayPartId getId() {
    return id;
  }

  public void setId(HourProfileDayPartId id) {
    this.id = id;
  }

  public HourProfileDayPartItem startHour(String startHour) {
    this.startHour = startHour;
    return this;
  }

   /**
   * Get startHour
   * @return startHour
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStartHour() {
    return startHour;
  }

  public void setStartHour(String startHour) {
    this.startHour = startHour;
  }

  public HourProfileDayPartItem endHour(String endHour) {
    this.endHour = endHour;
    return this;
  }

   /**
   * Get endHour
   * @return endHour
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEndHour() {
    return endHour;
  }

  public void setEndHour(String endHour) {
    this.endHour = endHour;
  }

  public HourProfileDayPartItem workedInHour(String workedInHour) {
    this.workedInHour = workedInHour;
    return this;
  }

   /**
   * Get workedInHour
   * @return workedInHour
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWorkedInHour() {
    return workedInHour;
  }

  public void setWorkedInHour(String workedInHour) {
    this.workedInHour = workedInHour;
  }

  public HourProfileDayPartItem workedInDay(Double workedInDay) {
    this.workedInDay = workedInDay;
    return this;
  }

   /**
   * Get workedInDay
   * minimum: 0.0
   * @return workedInDay
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getWorkedInDay() {
    return workedInDay;
  }

  public void setWorkedInDay(Double workedInDay) {
    this.workedInDay = workedInDay;
  }

  public HourProfileDayPartItem dayPart(Integer dayPart) {
    this.dayPart = dayPart;
    return this;
  }

   /**
   * Get dayPart
   * minimum: 1.0
   * maximum: 2.0
   * @return dayPart
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDayPart() {
    return dayPart;
  }

  public void setDayPart(Integer dayPart) {
    this.dayPart = dayPart;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HourProfileDayPartItem hourProfileDayPartItem = (HourProfileDayPartItem) o;
    return Objects.equals(this.id, hourProfileDayPartItem.id) &&
        Objects.equals(this.startHour, hourProfileDayPartItem.startHour) &&
        Objects.equals(this.endHour, hourProfileDayPartItem.endHour) &&
        Objects.equals(this.workedInHour, hourProfileDayPartItem.workedInHour) &&
        Objects.equals(this.workedInDay, hourProfileDayPartItem.workedInDay) &&
        Objects.equals(this.dayPart, hourProfileDayPartItem.dayPart);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, startHour, endHour, workedInHour, workedInDay, dayPart);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HourProfileDayPartItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    startHour: ").append(toIndentedString(startHour)).append("\n");
    sb.append("    endHour: ").append(toIndentedString(endHour)).append("\n");
    sb.append("    workedInHour: ").append(toIndentedString(workedInHour)).append("\n");
    sb.append("    workedInDay: ").append(toIndentedString(workedInDay)).append("\n");
    sb.append("    dayPart: ").append(toIndentedString(dayPart)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

