/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UserId;


/**
 * LinkedUserRelationItem
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:18:43.286+01:00")
public class LinkedUserRelationItem   {
  @SerializedName("id")
  private UserId id = null;

  @SerializedName("linkedUserId")
  private UserId linkedUserId = null;

  @SerializedName("linkedUserName")
  private String linkedUserName = null;

  @SerializedName("linkedUserPhoto")
  private String linkedUserPhoto = null;

  @SerializedName("linkedUserRelation")
  private String linkedUserRelation = null;

  public LinkedUserRelationItem id(UserId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserId getId() {
    return id;
  }

  public void setId(UserId id) {
    this.id = id;
  }

  public LinkedUserRelationItem linkedUserId(UserId linkedUserId) {
    this.linkedUserId = linkedUserId;
    return this;
  }

   /**
   * Get linkedUserId
   * @return linkedUserId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public UserId getLinkedUserId() {
    return linkedUserId;
  }

  public void setLinkedUserId(UserId linkedUserId) {
    this.linkedUserId = linkedUserId;
  }

  public LinkedUserRelationItem linkedUserName(String linkedUserName) {
    this.linkedUserName = linkedUserName;
    return this;
  }

   /**
   * Get linkedUserName
   * @return linkedUserName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLinkedUserName() {
    return linkedUserName;
  }

  public void setLinkedUserName(String linkedUserName) {
    this.linkedUserName = linkedUserName;
  }

  public LinkedUserRelationItem linkedUserPhoto(String linkedUserPhoto) {
    this.linkedUserPhoto = linkedUserPhoto;
    return this;
  }

   /**
   * Get linkedUserPhoto
   * @return linkedUserPhoto
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLinkedUserPhoto() {
    return linkedUserPhoto;
  }

  public void setLinkedUserPhoto(String linkedUserPhoto) {
    this.linkedUserPhoto = linkedUserPhoto;
  }

  public LinkedUserRelationItem linkedUserRelation(String linkedUserRelation) {
    this.linkedUserRelation = linkedUserRelation;
    return this;
  }

   /**
   * Get linkedUserRelation
   * @return linkedUserRelation
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLinkedUserRelation() {
    return linkedUserRelation;
  }

  public void setLinkedUserRelation(String linkedUserRelation) {
    this.linkedUserRelation = linkedUserRelation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkedUserRelationItem linkedUserRelationItem = (LinkedUserRelationItem) o;
    return Objects.equals(this.id, linkedUserRelationItem.id) &&
        Objects.equals(this.linkedUserId, linkedUserRelationItem.linkedUserId) &&
        Objects.equals(this.linkedUserName, linkedUserRelationItem.linkedUserName) &&
        Objects.equals(this.linkedUserPhoto, linkedUserRelationItem.linkedUserPhoto) &&
        Objects.equals(this.linkedUserRelation, linkedUserRelationItem.linkedUserRelation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, linkedUserId, linkedUserName, linkedUserPhoto, linkedUserRelation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkedUserRelationItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    linkedUserId: ").append(toIndentedString(linkedUserId)).append("\n");
    sb.append("    linkedUserName: ").append(toIndentedString(linkedUserName)).append("\n");
    sb.append("    linkedUserPhoto: ").append(toIndentedString(linkedUserPhoto)).append("\n");
    sb.append("    linkedUserRelation: ").append(toIndentedString(linkedUserRelation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

