/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LinkedUserRelationId;


/**
 * LinkedUserRelation
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:24:13.221+01:00")
public class LinkedUserRelation   {
  @SerializedName("linkedUserRelation")
  private String linkedUserRelation = null;

  @SerializedName("id")
  private LinkedUserRelationId id = null;

  public LinkedUserRelation linkedUserRelation(String linkedUserRelation) {
    this.linkedUserRelation = linkedUserRelation;
    return this;
  }

   /**
   * Get linkedUserRelation
   * @return linkedUserRelation
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLinkedUserRelation() {
    return linkedUserRelation;
  }

  public void setLinkedUserRelation(String linkedUserRelation) {
    this.linkedUserRelation = linkedUserRelation;
  }

  public LinkedUserRelation id(LinkedUserRelationId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public LinkedUserRelationId getId() {
    return id;
  }

  public void setId(LinkedUserRelationId id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkedUserRelation linkedUserRelation = (LinkedUserRelation) o;
    return Objects.equals(this.linkedUserRelation, linkedUserRelation.linkedUserRelation) &&
        Objects.equals(this.id, linkedUserRelation.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkedUserRelation, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkedUserRelation {\n");
    
    sb.append("    linkedUserRelation: ").append(toIndentedString(linkedUserRelation)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

