/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * OptionListValueObject
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:24:13.221+01:00")
public class OptionListValueObject   {
  @SerializedName("idValue")
  private String idValue = null;

  @SerializedName("listValueDescription")
  private String listValueDescription = null;

  @SerializedName("otherData")
  private String otherData = null;

  @SerializedName("displayPosition")
  private Integer displayPosition = null;

  @SerializedName("extraData")
  private List<Object> extraData = new ArrayList<Object>();

  public OptionListValueObject idValue(String idValue) {
    this.idValue = idValue;
    return this;
  }

   /**
   * Get idValue
   * @return idValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdValue() {
    return idValue;
  }

  public void setIdValue(String idValue) {
    this.idValue = idValue;
  }

  public OptionListValueObject listValueDescription(String listValueDescription) {
    this.listValueDescription = listValueDescription;
    return this;
  }

   /**
   * Get listValueDescription
   * @return listValueDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getListValueDescription() {
    return listValueDescription;
  }

  public void setListValueDescription(String listValueDescription) {
    this.listValueDescription = listValueDescription;
  }

  public OptionListValueObject otherData(String otherData) {
    this.otherData = otherData;
    return this;
  }

   /**
   * Get otherData
   * @return otherData
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOtherData() {
    return otherData;
  }

  public void setOtherData(String otherData) {
    this.otherData = otherData;
  }

  public OptionListValueObject displayPosition(Integer displayPosition) {
    this.displayPosition = displayPosition;
    return this;
  }

   /**
   * Get displayPosition
   * @return displayPosition
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDisplayPosition() {
    return displayPosition;
  }

  public void setDisplayPosition(Integer displayPosition) {
    this.displayPosition = displayPosition;
  }

  public OptionListValueObject extraData(List<Object> extraData) {
    this.extraData = extraData;
    return this;
  }

  public OptionListValueObject addExtraDataItem(Object extraDataItem) {
    this.extraData.add(extraDataItem);
    return this;
  }

   /**
   * Get extraData
   * @return extraData
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Object> getExtraData() {
    return extraData;
  }

  public void setExtraData(List<Object> extraData) {
    this.extraData = extraData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OptionListValueObject optionListValueObject = (OptionListValueObject) o;
    return Objects.equals(this.idValue, optionListValueObject.idValue) &&
        Objects.equals(this.listValueDescription, optionListValueObject.listValueDescription) &&
        Objects.equals(this.otherData, optionListValueObject.otherData) &&
        Objects.equals(this.displayPosition, optionListValueObject.displayPosition) &&
        Objects.equals(this.extraData, optionListValueObject.extraData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idValue, listValueDescription, otherData, displayPosition, extraData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OptionListValueObject {\n");
    
    sb.append("    idValue: ").append(toIndentedString(idValue)).append("\n");
    sb.append("    listValueDescription: ").append(toIndentedString(listValueDescription)).append("\n");
    sb.append("    otherData: ").append(toIndentedString(otherData)).append("\n");
    sb.append("    displayPosition: ").append(toIndentedString(displayPosition)).append("\n");
    sb.append("    extraData: ").append(toIndentedString(extraData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

