/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DaysOffBeanId;
import io.swagger.client.model.FileBeanId;
import io.swagger.client.model.LinkedManagerRelationItem;
import io.swagger.client.model.LinkedUserRelationItem;
import io.swagger.client.model.UserAddressItem;
import io.swagger.client.model.UserChildrenItem;
import io.swagger.client.model.UserCompanyOrganizationItem;
import io.swagger.client.model.UserId;
import io.swagger.client.model.UserLeaveVacationProfilesItem;
import io.swagger.client.model.UserPhonesItem;
import io.swagger.client.model.UserProductItem;
import io.swagger.client.model.UserProfileId;
import io.swagger.client.model.UserTokenDeviceConnectionItem;
import io.swagger.client.model.UserWellBeingVoteItem;
import io.swagger.client.model.UserWidgetsPrefItem;
import io.swagger.client.model.UserWorkContractsItem;
import io.swagger.client.model.UserWorkedHoursItem;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * UserFormBean
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:18:43.286+01:00")
public class UserFormBean   {
  @SerializedName("userCreate")
  private String userCreate = null;

  @SerializedName("dateCreate")
  private DateTime dateCreate = null;

  @SerializedName("userUpdate")
  private String userUpdate = null;

  @SerializedName("dateUpdate")
  private DateTime dateUpdate = null;

  /**
   * Gets or Sets formMode
   */
  public enum FormModeEnum {
    @SerializedName("EDIT_MODE")
    EDIT_MODE("EDIT_MODE"),
    
    @SerializedName("CREATE_MODE")
    CREATE_MODE("CREATE_MODE"),
    
    @SerializedName("DISPLAY_MODE")
    DISPLAY_MODE("DISPLAY_MODE");

    private String value;

    FormModeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("formMode")
  private FormModeEnum formMode = null;

  @SerializedName("internalCode")
  private String internalCode = null;

  @SerializedName("locale")
  private String locale = null;

  @SerializedName("id")
  private UserId id = null;

  @SerializedName("companyDetail")
  private String companyDetail = null;

  @SerializedName("userGender")
  private String userGender = null;

  @SerializedName("userFirstName")
  private String userFirstName = null;

  @SerializedName("userLastName")
  private String userLastName = null;

  @SerializedName("userEmail")
  private String userEmail = null;

  @SerializedName("userEmailTempKey")
  private String userEmailTempKey = null;

  @SerializedName("userSerial")
  private String userSerial = null;

  @SerializedName("userPwd")
  private String userPwd = null;

  @SerializedName("userLocale")
  private String userLocale = null;

  @SerializedName("userFunction")
  private String userFunction = null;

  @SerializedName("userBirthDay")
  private DateTime userBirthDay = null;

  @SerializedName("idUserProfile")
  private UserProfileId idUserProfile = null;

  @SerializedName("flagEmailAddressHasChanged")
  private Boolean flagEmailAddressHasChanged = false;

  @SerializedName("userPhoto")
  private String userPhoto = null;

  @SerializedName("userPhotoHasChanged")
  private Boolean userPhotoHasChanged = false;

  @SerializedName("userPhotoFileBeanId")
  private FileBeanId userPhotoFileBeanId = null;

  @SerializedName("userPayroll")
  private Double userPayroll = null;

  @SerializedName("userWorkCategory")
  private String userWorkCategory = null;

  @SerializedName("userWorkLevel")
  private String userWorkLevel = null;

  @SerializedName("userEchelon")
  private String userEchelon = null;

  @SerializedName("userTimeZone")
  private String userTimeZone = null;

  @SerializedName("userHiringDate")
  private DateTime userHiringDate = null;

  @SerializedName("userDepartureDate")
  private DateTime userDepartureDate = null;

  @SerializedName("appRole")
  private String appRole = null;

  @SerializedName("userDaysOffId")
  private DaysOffBeanId userDaysOffId = null;

  @SerializedName("tco")
  private Double tco = null;

  @SerializedName("linkedUserRelation")
  private List<LinkedUserRelationItem> linkedUserRelation = new ArrayList<LinkedUserRelationItem>();

  @SerializedName("deletedLinkedUserRelation")
  private List<LinkedUserRelationItem> deletedLinkedUserRelation = new ArrayList<LinkedUserRelationItem>();

  @SerializedName("linkedManagerRelation")
  private List<LinkedManagerRelationItem> linkedManagerRelation = new ArrayList<LinkedManagerRelationItem>();

  @SerializedName("deletedLinkedManagerRelation")
  private List<LinkedManagerRelationItem> deletedLinkedManagerRelation = new ArrayList<LinkedManagerRelationItem>();

  @SerializedName("userWorkedHours")
  private List<UserWorkedHoursItem> userWorkedHours = new ArrayList<UserWorkedHoursItem>();

  @SerializedName("userWorkContracts")
  private List<UserWorkContractsItem> userWorkContracts = new ArrayList<UserWorkContractsItem>();

  @SerializedName("userLeaveVacationProfiles")
  private List<UserLeaveVacationProfilesItem> userLeaveVacationProfiles = new ArrayList<UserLeaveVacationProfilesItem>();

  @SerializedName("userMaritalStatus")
  private String userMaritalStatus = null;

  @SerializedName("userLinkConnection")
  private String userLinkConnection = null;

  @SerializedName("userAddress")
  private List<UserAddressItem> userAddress = new ArrayList<UserAddressItem>();

  @SerializedName("userPhones")
  private List<UserPhonesItem> userPhones = new ArrayList<UserPhonesItem>();

  @SerializedName("userChildren")
  private List<UserChildrenItem> userChildren = new ArrayList<UserChildrenItem>();

  @SerializedName("userCompanyOrganizations")
  private List<UserCompanyOrganizationItem> userCompanyOrganizations = new ArrayList<UserCompanyOrganizationItem>();

  @SerializedName("userTokenDeviceConnections")
  private List<UserTokenDeviceConnectionItem> userTokenDeviceConnections = new ArrayList<UserTokenDeviceConnectionItem>();

  @SerializedName("userWidgetsPref")
  private List<UserWidgetsPrefItem> userWidgetsPref = new ArrayList<UserWidgetsPrefItem>();

  @SerializedName("userWellBeingVotes")
  private List<UserWellBeingVoteItem> userWellBeingVotes = new ArrayList<UserWellBeingVoteItem>();

  @SerializedName("hasAccessToAzuneedPortal")
  private Boolean hasAccessToAzuneedPortal = false;

  @SerializedName("userProducts")
  private List<UserProductItem> userProducts = new ArrayList<UserProductItem>();

  @SerializedName("anAdmin")
  private Boolean anAdmin = false;

  @SerializedName("idCompany")
  private String idCompany = null;

  public UserFormBean userCreate(String userCreate) {
    this.userCreate = userCreate;
    return this;
  }

   /**
   * Get userCreate
   * @return userCreate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserCreate() {
    return userCreate;
  }

  public void setUserCreate(String userCreate) {
    this.userCreate = userCreate;
  }

  public UserFormBean dateCreate(DateTime dateCreate) {
    this.dateCreate = dateCreate;
    return this;
  }

   /**
   * Get dateCreate
   * @return dateCreate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateCreate() {
    return dateCreate;
  }

  public void setDateCreate(DateTime dateCreate) {
    this.dateCreate = dateCreate;
  }

  public UserFormBean userUpdate(String userUpdate) {
    this.userUpdate = userUpdate;
    return this;
  }

   /**
   * Get userUpdate
   * @return userUpdate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserUpdate() {
    return userUpdate;
  }

  public void setUserUpdate(String userUpdate) {
    this.userUpdate = userUpdate;
  }

  public UserFormBean dateUpdate(DateTime dateUpdate) {
    this.dateUpdate = dateUpdate;
    return this;
  }

   /**
   * Get dateUpdate
   * @return dateUpdate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateUpdate() {
    return dateUpdate;
  }

  public void setDateUpdate(DateTime dateUpdate) {
    this.dateUpdate = dateUpdate;
  }

  public UserFormBean formMode(FormModeEnum formMode) {
    this.formMode = formMode;
    return this;
  }

   /**
   * Get formMode
   * @return formMode
  **/
  @ApiModelProperty(example = "null", value = "")
  public FormModeEnum getFormMode() {
    return formMode;
  }

  public void setFormMode(FormModeEnum formMode) {
    this.formMode = formMode;
  }

  public UserFormBean internalCode(String internalCode) {
    this.internalCode = internalCode;
    return this;
  }

   /**
   * Get internalCode
   * @return internalCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInternalCode() {
    return internalCode;
  }

  public void setInternalCode(String internalCode) {
    this.internalCode = internalCode;
  }

  public UserFormBean locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public UserFormBean id(UserId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserId getId() {
    return id;
  }

  public void setId(UserId id) {
    this.id = id;
  }

  public UserFormBean companyDetail(String companyDetail) {
    this.companyDetail = companyDetail;
    return this;
  }

   /**
   * Get companyDetail
   * @return companyDetail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCompanyDetail() {
    return companyDetail;
  }

  public void setCompanyDetail(String companyDetail) {
    this.companyDetail = companyDetail;
  }

  public UserFormBean userGender(String userGender) {
    this.userGender = userGender;
    return this;
  }

   /**
   * Get userGender
   * @return userGender
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getUserGender() {
    return userGender;
  }

  public void setUserGender(String userGender) {
    this.userGender = userGender;
  }

  public UserFormBean userFirstName(String userFirstName) {
    this.userFirstName = userFirstName;
    return this;
  }

   /**
   * Get userFirstName
   * @return userFirstName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getUserFirstName() {
    return userFirstName;
  }

  public void setUserFirstName(String userFirstName) {
    this.userFirstName = userFirstName;
  }

  public UserFormBean userLastName(String userLastName) {
    this.userLastName = userLastName;
    return this;
  }

   /**
   * Get userLastName
   * @return userLastName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getUserLastName() {
    return userLastName;
  }

  public void setUserLastName(String userLastName) {
    this.userLastName = userLastName;
  }

  public UserFormBean userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

   /**
   * Get userEmail
   * @return userEmail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public UserFormBean userEmailTempKey(String userEmailTempKey) {
    this.userEmailTempKey = userEmailTempKey;
    return this;
  }

   /**
   * Get userEmailTempKey
   * @return userEmailTempKey
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserEmailTempKey() {
    return userEmailTempKey;
  }

  public void setUserEmailTempKey(String userEmailTempKey) {
    this.userEmailTempKey = userEmailTempKey;
  }

  public UserFormBean userSerial(String userSerial) {
    this.userSerial = userSerial;
    return this;
  }

   /**
   * Get userSerial
   * @return userSerial
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserSerial() {
    return userSerial;
  }

  public void setUserSerial(String userSerial) {
    this.userSerial = userSerial;
  }

  public UserFormBean userPwd(String userPwd) {
    this.userPwd = userPwd;
    return this;
  }

   /**
   * Get userPwd
   * @return userPwd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserPwd() {
    return userPwd;
  }

  public void setUserPwd(String userPwd) {
    this.userPwd = userPwd;
  }

  public UserFormBean userLocale(String userLocale) {
    this.userLocale = userLocale;
    return this;
  }

   /**
   * Get userLocale
   * @return userLocale
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserLocale() {
    return userLocale;
  }

  public void setUserLocale(String userLocale) {
    this.userLocale = userLocale;
  }

  public UserFormBean userFunction(String userFunction) {
    this.userFunction = userFunction;
    return this;
  }

   /**
   * Get userFunction
   * @return userFunction
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserFunction() {
    return userFunction;
  }

  public void setUserFunction(String userFunction) {
    this.userFunction = userFunction;
  }

  public UserFormBean userBirthDay(DateTime userBirthDay) {
    this.userBirthDay = userBirthDay;
    return this;
  }

   /**
   * Get userBirthDay
   * @return userBirthDay
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getUserBirthDay() {
    return userBirthDay;
  }

  public void setUserBirthDay(DateTime userBirthDay) {
    this.userBirthDay = userBirthDay;
  }

  public UserFormBean idUserProfile(UserProfileId idUserProfile) {
    this.idUserProfile = idUserProfile;
    return this;
  }

   /**
   * Get idUserProfile
   * @return idUserProfile
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserProfileId getIdUserProfile() {
    return idUserProfile;
  }

  public void setIdUserProfile(UserProfileId idUserProfile) {
    this.idUserProfile = idUserProfile;
  }

  public UserFormBean flagEmailAddressHasChanged(Boolean flagEmailAddressHasChanged) {
    this.flagEmailAddressHasChanged = flagEmailAddressHasChanged;
    return this;
  }

   /**
   * Get flagEmailAddressHasChanged
   * @return flagEmailAddressHasChanged
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getFlagEmailAddressHasChanged() {
    return flagEmailAddressHasChanged;
  }

  public void setFlagEmailAddressHasChanged(Boolean flagEmailAddressHasChanged) {
    this.flagEmailAddressHasChanged = flagEmailAddressHasChanged;
  }

  public UserFormBean userPhoto(String userPhoto) {
    this.userPhoto = userPhoto;
    return this;
  }

   /**
   * Get userPhoto
   * @return userPhoto
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserPhoto() {
    return userPhoto;
  }

  public void setUserPhoto(String userPhoto) {
    this.userPhoto = userPhoto;
  }

  public UserFormBean userPhotoHasChanged(Boolean userPhotoHasChanged) {
    this.userPhotoHasChanged = userPhotoHasChanged;
    return this;
  }

   /**
   * Get userPhotoHasChanged
   * @return userPhotoHasChanged
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getUserPhotoHasChanged() {
    return userPhotoHasChanged;
  }

  public void setUserPhotoHasChanged(Boolean userPhotoHasChanged) {
    this.userPhotoHasChanged = userPhotoHasChanged;
  }

  public UserFormBean userPhotoFileBeanId(FileBeanId userPhotoFileBeanId) {
    this.userPhotoFileBeanId = userPhotoFileBeanId;
    return this;
  }

   /**
   * Get userPhotoFileBeanId
   * @return userPhotoFileBeanId
  **/
  @ApiModelProperty(example = "null", value = "")
  public FileBeanId getUserPhotoFileBeanId() {
    return userPhotoFileBeanId;
  }

  public void setUserPhotoFileBeanId(FileBeanId userPhotoFileBeanId) {
    this.userPhotoFileBeanId = userPhotoFileBeanId;
  }

  public UserFormBean userPayroll(Double userPayroll) {
    this.userPayroll = userPayroll;
    return this;
  }

   /**
   * Get userPayroll
   * @return userPayroll
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getUserPayroll() {
    return userPayroll;
  }

  public void setUserPayroll(Double userPayroll) {
    this.userPayroll = userPayroll;
  }

  public UserFormBean userWorkCategory(String userWorkCategory) {
    this.userWorkCategory = userWorkCategory;
    return this;
  }

   /**
   * Get userWorkCategory
   * @return userWorkCategory
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserWorkCategory() {
    return userWorkCategory;
  }

  public void setUserWorkCategory(String userWorkCategory) {
    this.userWorkCategory = userWorkCategory;
  }

  public UserFormBean userWorkLevel(String userWorkLevel) {
    this.userWorkLevel = userWorkLevel;
    return this;
  }

   /**
   * Get userWorkLevel
   * @return userWorkLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserWorkLevel() {
    return userWorkLevel;
  }

  public void setUserWorkLevel(String userWorkLevel) {
    this.userWorkLevel = userWorkLevel;
  }

  public UserFormBean userEchelon(String userEchelon) {
    this.userEchelon = userEchelon;
    return this;
  }

   /**
   * Get userEchelon
   * @return userEchelon
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserEchelon() {
    return userEchelon;
  }

  public void setUserEchelon(String userEchelon) {
    this.userEchelon = userEchelon;
  }

  public UserFormBean userTimeZone(String userTimeZone) {
    this.userTimeZone = userTimeZone;
    return this;
  }

   /**
   * Get userTimeZone
   * @return userTimeZone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserTimeZone() {
    return userTimeZone;
  }

  public void setUserTimeZone(String userTimeZone) {
    this.userTimeZone = userTimeZone;
  }

  public UserFormBean userHiringDate(DateTime userHiringDate) {
    this.userHiringDate = userHiringDate;
    return this;
  }

   /**
   * Get userHiringDate
   * @return userHiringDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getUserHiringDate() {
    return userHiringDate;
  }

  public void setUserHiringDate(DateTime userHiringDate) {
    this.userHiringDate = userHiringDate;
  }

  public UserFormBean userDepartureDate(DateTime userDepartureDate) {
    this.userDepartureDate = userDepartureDate;
    return this;
  }

   /**
   * Get userDepartureDate
   * @return userDepartureDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getUserDepartureDate() {
    return userDepartureDate;
  }

  public void setUserDepartureDate(DateTime userDepartureDate) {
    this.userDepartureDate = userDepartureDate;
  }

  public UserFormBean appRole(String appRole) {
    this.appRole = appRole;
    return this;
  }

   /**
   * Get appRole
   * @return appRole
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAppRole() {
    return appRole;
  }

  public void setAppRole(String appRole) {
    this.appRole = appRole;
  }

  public UserFormBean userDaysOffId(DaysOffBeanId userDaysOffId) {
    this.userDaysOffId = userDaysOffId;
    return this;
  }

   /**
   * Get userDaysOffId
   * @return userDaysOffId
  **/
  @ApiModelProperty(example = "null", value = "")
  public DaysOffBeanId getUserDaysOffId() {
    return userDaysOffId;
  }

  public void setUserDaysOffId(DaysOffBeanId userDaysOffId) {
    this.userDaysOffId = userDaysOffId;
  }

  public UserFormBean tco(Double tco) {
    this.tco = tco;
    return this;
  }

   /**
   * Get tco
   * @return tco
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTco() {
    return tco;
  }

  public void setTco(Double tco) {
    this.tco = tco;
  }

  public UserFormBean linkedUserRelation(List<LinkedUserRelationItem> linkedUserRelation) {
    this.linkedUserRelation = linkedUserRelation;
    return this;
  }

  public UserFormBean addLinkedUserRelationItem(LinkedUserRelationItem linkedUserRelationItem) {
    this.linkedUserRelation.add(linkedUserRelationItem);
    return this;
  }

   /**
   * Get linkedUserRelation
   * @return linkedUserRelation
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LinkedUserRelationItem> getLinkedUserRelation() {
    return linkedUserRelation;
  }

  public void setLinkedUserRelation(List<LinkedUserRelationItem> linkedUserRelation) {
    this.linkedUserRelation = linkedUserRelation;
  }

  public UserFormBean deletedLinkedUserRelation(List<LinkedUserRelationItem> deletedLinkedUserRelation) {
    this.deletedLinkedUserRelation = deletedLinkedUserRelation;
    return this;
  }

  public UserFormBean addDeletedLinkedUserRelationItem(LinkedUserRelationItem deletedLinkedUserRelationItem) {
    this.deletedLinkedUserRelation.add(deletedLinkedUserRelationItem);
    return this;
  }

   /**
   * Get deletedLinkedUserRelation
   * @return deletedLinkedUserRelation
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LinkedUserRelationItem> getDeletedLinkedUserRelation() {
    return deletedLinkedUserRelation;
  }

  public void setDeletedLinkedUserRelation(List<LinkedUserRelationItem> deletedLinkedUserRelation) {
    this.deletedLinkedUserRelation = deletedLinkedUserRelation;
  }

  public UserFormBean linkedManagerRelation(List<LinkedManagerRelationItem> linkedManagerRelation) {
    this.linkedManagerRelation = linkedManagerRelation;
    return this;
  }

  public UserFormBean addLinkedManagerRelationItem(LinkedManagerRelationItem linkedManagerRelationItem) {
    this.linkedManagerRelation.add(linkedManagerRelationItem);
    return this;
  }

   /**
   * Get linkedManagerRelation
   * @return linkedManagerRelation
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LinkedManagerRelationItem> getLinkedManagerRelation() {
    return linkedManagerRelation;
  }

  public void setLinkedManagerRelation(List<LinkedManagerRelationItem> linkedManagerRelation) {
    this.linkedManagerRelation = linkedManagerRelation;
  }

  public UserFormBean deletedLinkedManagerRelation(List<LinkedManagerRelationItem> deletedLinkedManagerRelation) {
    this.deletedLinkedManagerRelation = deletedLinkedManagerRelation;
    return this;
  }

  public UserFormBean addDeletedLinkedManagerRelationItem(LinkedManagerRelationItem deletedLinkedManagerRelationItem) {
    this.deletedLinkedManagerRelation.add(deletedLinkedManagerRelationItem);
    return this;
  }

   /**
   * Get deletedLinkedManagerRelation
   * @return deletedLinkedManagerRelation
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LinkedManagerRelationItem> getDeletedLinkedManagerRelation() {
    return deletedLinkedManagerRelation;
  }

  public void setDeletedLinkedManagerRelation(List<LinkedManagerRelationItem> deletedLinkedManagerRelation) {
    this.deletedLinkedManagerRelation = deletedLinkedManagerRelation;
  }

  public UserFormBean userWorkedHours(List<UserWorkedHoursItem> userWorkedHours) {
    this.userWorkedHours = userWorkedHours;
    return this;
  }

  public UserFormBean addUserWorkedHoursItem(UserWorkedHoursItem userWorkedHoursItem) {
    this.userWorkedHours.add(userWorkedHoursItem);
    return this;
  }

   /**
   * Get userWorkedHours
   * @return userWorkedHours
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserWorkedHoursItem> getUserWorkedHours() {
    return userWorkedHours;
  }

  public void setUserWorkedHours(List<UserWorkedHoursItem> userWorkedHours) {
    this.userWorkedHours = userWorkedHours;
  }

  public UserFormBean userWorkContracts(List<UserWorkContractsItem> userWorkContracts) {
    this.userWorkContracts = userWorkContracts;
    return this;
  }

  public UserFormBean addUserWorkContractsItem(UserWorkContractsItem userWorkContractsItem) {
    this.userWorkContracts.add(userWorkContractsItem);
    return this;
  }

   /**
   * Get userWorkContracts
   * @return userWorkContracts
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserWorkContractsItem> getUserWorkContracts() {
    return userWorkContracts;
  }

  public void setUserWorkContracts(List<UserWorkContractsItem> userWorkContracts) {
    this.userWorkContracts = userWorkContracts;
  }

  public UserFormBean userLeaveVacationProfiles(List<UserLeaveVacationProfilesItem> userLeaveVacationProfiles) {
    this.userLeaveVacationProfiles = userLeaveVacationProfiles;
    return this;
  }

  public UserFormBean addUserLeaveVacationProfilesItem(UserLeaveVacationProfilesItem userLeaveVacationProfilesItem) {
    this.userLeaveVacationProfiles.add(userLeaveVacationProfilesItem);
    return this;
  }

   /**
   * Get userLeaveVacationProfiles
   * @return userLeaveVacationProfiles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserLeaveVacationProfilesItem> getUserLeaveVacationProfiles() {
    return userLeaveVacationProfiles;
  }

  public void setUserLeaveVacationProfiles(List<UserLeaveVacationProfilesItem> userLeaveVacationProfiles) {
    this.userLeaveVacationProfiles = userLeaveVacationProfiles;
  }

  public UserFormBean userMaritalStatus(String userMaritalStatus) {
    this.userMaritalStatus = userMaritalStatus;
    return this;
  }

   /**
   * Get userMaritalStatus
   * @return userMaritalStatus
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserMaritalStatus() {
    return userMaritalStatus;
  }

  public void setUserMaritalStatus(String userMaritalStatus) {
    this.userMaritalStatus = userMaritalStatus;
  }

  public UserFormBean userLinkConnection(String userLinkConnection) {
    this.userLinkConnection = userLinkConnection;
    return this;
  }

   /**
   * Get userLinkConnection
   * @return userLinkConnection
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserLinkConnection() {
    return userLinkConnection;
  }

  public void setUserLinkConnection(String userLinkConnection) {
    this.userLinkConnection = userLinkConnection;
  }

  public UserFormBean userAddress(List<UserAddressItem> userAddress) {
    this.userAddress = userAddress;
    return this;
  }

  public UserFormBean addUserAddressItem(UserAddressItem userAddressItem) {
    this.userAddress.add(userAddressItem);
    return this;
  }

   /**
   * Get userAddress
   * @return userAddress
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserAddressItem> getUserAddress() {
    return userAddress;
  }

  public void setUserAddress(List<UserAddressItem> userAddress) {
    this.userAddress = userAddress;
  }

  public UserFormBean userPhones(List<UserPhonesItem> userPhones) {
    this.userPhones = userPhones;
    return this;
  }

  public UserFormBean addUserPhonesItem(UserPhonesItem userPhonesItem) {
    this.userPhones.add(userPhonesItem);
    return this;
  }

   /**
   * Get userPhones
   * @return userPhones
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserPhonesItem> getUserPhones() {
    return userPhones;
  }

  public void setUserPhones(List<UserPhonesItem> userPhones) {
    this.userPhones = userPhones;
  }

  public UserFormBean userChildren(List<UserChildrenItem> userChildren) {
    this.userChildren = userChildren;
    return this;
  }

  public UserFormBean addUserChildrenItem(UserChildrenItem userChildrenItem) {
    this.userChildren.add(userChildrenItem);
    return this;
  }

   /**
   * Get userChildren
   * @return userChildren
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserChildrenItem> getUserChildren() {
    return userChildren;
  }

  public void setUserChildren(List<UserChildrenItem> userChildren) {
    this.userChildren = userChildren;
  }

  public UserFormBean userCompanyOrganizations(List<UserCompanyOrganizationItem> userCompanyOrganizations) {
    this.userCompanyOrganizations = userCompanyOrganizations;
    return this;
  }

  public UserFormBean addUserCompanyOrganizationsItem(UserCompanyOrganizationItem userCompanyOrganizationsItem) {
    this.userCompanyOrganizations.add(userCompanyOrganizationsItem);
    return this;
  }

   /**
   * Get userCompanyOrganizations
   * @return userCompanyOrganizations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserCompanyOrganizationItem> getUserCompanyOrganizations() {
    return userCompanyOrganizations;
  }

  public void setUserCompanyOrganizations(List<UserCompanyOrganizationItem> userCompanyOrganizations) {
    this.userCompanyOrganizations = userCompanyOrganizations;
  }

  public UserFormBean userTokenDeviceConnections(List<UserTokenDeviceConnectionItem> userTokenDeviceConnections) {
    this.userTokenDeviceConnections = userTokenDeviceConnections;
    return this;
  }

  public UserFormBean addUserTokenDeviceConnectionsItem(UserTokenDeviceConnectionItem userTokenDeviceConnectionsItem) {
    this.userTokenDeviceConnections.add(userTokenDeviceConnectionsItem);
    return this;
  }

   /**
   * Get userTokenDeviceConnections
   * @return userTokenDeviceConnections
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserTokenDeviceConnectionItem> getUserTokenDeviceConnections() {
    return userTokenDeviceConnections;
  }

  public void setUserTokenDeviceConnections(List<UserTokenDeviceConnectionItem> userTokenDeviceConnections) {
    this.userTokenDeviceConnections = userTokenDeviceConnections;
  }

  public UserFormBean userWidgetsPref(List<UserWidgetsPrefItem> userWidgetsPref) {
    this.userWidgetsPref = userWidgetsPref;
    return this;
  }

  public UserFormBean addUserWidgetsPrefItem(UserWidgetsPrefItem userWidgetsPrefItem) {
    this.userWidgetsPref.add(userWidgetsPrefItem);
    return this;
  }

   /**
   * Get userWidgetsPref
   * @return userWidgetsPref
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserWidgetsPrefItem> getUserWidgetsPref() {
    return userWidgetsPref;
  }

  public void setUserWidgetsPref(List<UserWidgetsPrefItem> userWidgetsPref) {
    this.userWidgetsPref = userWidgetsPref;
  }

  public UserFormBean userWellBeingVotes(List<UserWellBeingVoteItem> userWellBeingVotes) {
    this.userWellBeingVotes = userWellBeingVotes;
    return this;
  }

  public UserFormBean addUserWellBeingVotesItem(UserWellBeingVoteItem userWellBeingVotesItem) {
    this.userWellBeingVotes.add(userWellBeingVotesItem);
    return this;
  }

   /**
   * Get userWellBeingVotes
   * @return userWellBeingVotes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserWellBeingVoteItem> getUserWellBeingVotes() {
    return userWellBeingVotes;
  }

  public void setUserWellBeingVotes(List<UserWellBeingVoteItem> userWellBeingVotes) {
    this.userWellBeingVotes = userWellBeingVotes;
  }

  public UserFormBean hasAccessToAzuneedPortal(Boolean hasAccessToAzuneedPortal) {
    this.hasAccessToAzuneedPortal = hasAccessToAzuneedPortal;
    return this;
  }

   /**
   * Get hasAccessToAzuneedPortal
   * @return hasAccessToAzuneedPortal
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getHasAccessToAzuneedPortal() {
    return hasAccessToAzuneedPortal;
  }

  public void setHasAccessToAzuneedPortal(Boolean hasAccessToAzuneedPortal) {
    this.hasAccessToAzuneedPortal = hasAccessToAzuneedPortal;
  }

  public UserFormBean userProducts(List<UserProductItem> userProducts) {
    this.userProducts = userProducts;
    return this;
  }

  public UserFormBean addUserProductsItem(UserProductItem userProductsItem) {
    this.userProducts.add(userProductsItem);
    return this;
  }

   /**
   * Get userProducts
   * @return userProducts
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserProductItem> getUserProducts() {
    return userProducts;
  }

  public void setUserProducts(List<UserProductItem> userProducts) {
    this.userProducts = userProducts;
  }

  public UserFormBean anAdmin(Boolean anAdmin) {
    this.anAdmin = anAdmin;
    return this;
  }

   /**
   * Get anAdmin
   * @return anAdmin
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getAnAdmin() {
    return anAdmin;
  }

  public void setAnAdmin(Boolean anAdmin) {
    this.anAdmin = anAdmin;
  }

  public UserFormBean idCompany(String idCompany) {
    this.idCompany = idCompany;
    return this;
  }

   /**
   * Get idCompany
   * @return idCompany
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdCompany() {
    return idCompany;
  }

  public void setIdCompany(String idCompany) {
    this.idCompany = idCompany;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserFormBean userFormBean = (UserFormBean) o;
    return Objects.equals(this.userCreate, userFormBean.userCreate) &&
        Objects.equals(this.dateCreate, userFormBean.dateCreate) &&
        Objects.equals(this.userUpdate, userFormBean.userUpdate) &&
        Objects.equals(this.dateUpdate, userFormBean.dateUpdate) &&
        Objects.equals(this.formMode, userFormBean.formMode) &&
        Objects.equals(this.internalCode, userFormBean.internalCode) &&
        Objects.equals(this.locale, userFormBean.locale) &&
        Objects.equals(this.id, userFormBean.id) &&
        Objects.equals(this.companyDetail, userFormBean.companyDetail) &&
        Objects.equals(this.userGender, userFormBean.userGender) &&
        Objects.equals(this.userFirstName, userFormBean.userFirstName) &&
        Objects.equals(this.userLastName, userFormBean.userLastName) &&
        Objects.equals(this.userEmail, userFormBean.userEmail) &&
        Objects.equals(this.userEmailTempKey, userFormBean.userEmailTempKey) &&
        Objects.equals(this.userSerial, userFormBean.userSerial) &&
        Objects.equals(this.userPwd, userFormBean.userPwd) &&
        Objects.equals(this.userLocale, userFormBean.userLocale) &&
        Objects.equals(this.userFunction, userFormBean.userFunction) &&
        Objects.equals(this.userBirthDay, userFormBean.userBirthDay) &&
        Objects.equals(this.idUserProfile, userFormBean.idUserProfile) &&
        Objects.equals(this.flagEmailAddressHasChanged, userFormBean.flagEmailAddressHasChanged) &&
        Objects.equals(this.userPhoto, userFormBean.userPhoto) &&
        Objects.equals(this.userPhotoHasChanged, userFormBean.userPhotoHasChanged) &&
        Objects.equals(this.userPhotoFileBeanId, userFormBean.userPhotoFileBeanId) &&
        Objects.equals(this.userPayroll, userFormBean.userPayroll) &&
        Objects.equals(this.userWorkCategory, userFormBean.userWorkCategory) &&
        Objects.equals(this.userWorkLevel, userFormBean.userWorkLevel) &&
        Objects.equals(this.userEchelon, userFormBean.userEchelon) &&
        Objects.equals(this.userTimeZone, userFormBean.userTimeZone) &&
        Objects.equals(this.userHiringDate, userFormBean.userHiringDate) &&
        Objects.equals(this.userDepartureDate, userFormBean.userDepartureDate) &&
        Objects.equals(this.appRole, userFormBean.appRole) &&
        Objects.equals(this.userDaysOffId, userFormBean.userDaysOffId) &&
        Objects.equals(this.tco, userFormBean.tco) &&
        Objects.equals(this.linkedUserRelation, userFormBean.linkedUserRelation) &&
        Objects.equals(this.deletedLinkedUserRelation, userFormBean.deletedLinkedUserRelation) &&
        Objects.equals(this.linkedManagerRelation, userFormBean.linkedManagerRelation) &&
        Objects.equals(this.deletedLinkedManagerRelation, userFormBean.deletedLinkedManagerRelation) &&
        Objects.equals(this.userWorkedHours, userFormBean.userWorkedHours) &&
        Objects.equals(this.userWorkContracts, userFormBean.userWorkContracts) &&
        Objects.equals(this.userLeaveVacationProfiles, userFormBean.userLeaveVacationProfiles) &&
        Objects.equals(this.userMaritalStatus, userFormBean.userMaritalStatus) &&
        Objects.equals(this.userLinkConnection, userFormBean.userLinkConnection) &&
        Objects.equals(this.userAddress, userFormBean.userAddress) &&
        Objects.equals(this.userPhones, userFormBean.userPhones) &&
        Objects.equals(this.userChildren, userFormBean.userChildren) &&
        Objects.equals(this.userCompanyOrganizations, userFormBean.userCompanyOrganizations) &&
        Objects.equals(this.userTokenDeviceConnections, userFormBean.userTokenDeviceConnections) &&
        Objects.equals(this.userWidgetsPref, userFormBean.userWidgetsPref) &&
        Objects.equals(this.userWellBeingVotes, userFormBean.userWellBeingVotes) &&
        Objects.equals(this.hasAccessToAzuneedPortal, userFormBean.hasAccessToAzuneedPortal) &&
        Objects.equals(this.userProducts, userFormBean.userProducts) &&
        Objects.equals(this.anAdmin, userFormBean.anAdmin) &&
        Objects.equals(this.idCompany, userFormBean.idCompany);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userCreate, dateCreate, userUpdate, dateUpdate, formMode, internalCode, locale, id, companyDetail, userGender, userFirstName, userLastName, userEmail, userEmailTempKey, userSerial, userPwd, userLocale, userFunction, userBirthDay, idUserProfile, flagEmailAddressHasChanged, userPhoto, userPhotoHasChanged, userPhotoFileBeanId, userPayroll, userWorkCategory, userWorkLevel, userEchelon, userTimeZone, userHiringDate, userDepartureDate, appRole, userDaysOffId, tco, linkedUserRelation, deletedLinkedUserRelation, linkedManagerRelation, deletedLinkedManagerRelation, userWorkedHours, userWorkContracts, userLeaveVacationProfiles, userMaritalStatus, userLinkConnection, userAddress, userPhones, userChildren, userCompanyOrganizations, userTokenDeviceConnections, userWidgetsPref, userWellBeingVotes, hasAccessToAzuneedPortal, userProducts, anAdmin, idCompany);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserFormBean {\n");
    
    sb.append("    userCreate: ").append(toIndentedString(userCreate)).append("\n");
    sb.append("    dateCreate: ").append(toIndentedString(dateCreate)).append("\n");
    sb.append("    userUpdate: ").append(toIndentedString(userUpdate)).append("\n");
    sb.append("    dateUpdate: ").append(toIndentedString(dateUpdate)).append("\n");
    sb.append("    formMode: ").append(toIndentedString(formMode)).append("\n");
    sb.append("    internalCode: ").append(toIndentedString(internalCode)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    companyDetail: ").append(toIndentedString(companyDetail)).append("\n");
    sb.append("    userGender: ").append(toIndentedString(userGender)).append("\n");
    sb.append("    userFirstName: ").append(toIndentedString(userFirstName)).append("\n");
    sb.append("    userLastName: ").append(toIndentedString(userLastName)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    userEmailTempKey: ").append(toIndentedString(userEmailTempKey)).append("\n");
    sb.append("    userSerial: ").append(toIndentedString(userSerial)).append("\n");
    sb.append("    userPwd: ").append(toIndentedString(userPwd)).append("\n");
    sb.append("    userLocale: ").append(toIndentedString(userLocale)).append("\n");
    sb.append("    userFunction: ").append(toIndentedString(userFunction)).append("\n");
    sb.append("    userBirthDay: ").append(toIndentedString(userBirthDay)).append("\n");
    sb.append("    idUserProfile: ").append(toIndentedString(idUserProfile)).append("\n");
    sb.append("    flagEmailAddressHasChanged: ").append(toIndentedString(flagEmailAddressHasChanged)).append("\n");
    sb.append("    userPhoto: ").append(toIndentedString(userPhoto)).append("\n");
    sb.append("    userPhotoHasChanged: ").append(toIndentedString(userPhotoHasChanged)).append("\n");
    sb.append("    userPhotoFileBeanId: ").append(toIndentedString(userPhotoFileBeanId)).append("\n");
    sb.append("    userPayroll: ").append(toIndentedString(userPayroll)).append("\n");
    sb.append("    userWorkCategory: ").append(toIndentedString(userWorkCategory)).append("\n");
    sb.append("    userWorkLevel: ").append(toIndentedString(userWorkLevel)).append("\n");
    sb.append("    userEchelon: ").append(toIndentedString(userEchelon)).append("\n");
    sb.append("    userTimeZone: ").append(toIndentedString(userTimeZone)).append("\n");
    sb.append("    userHiringDate: ").append(toIndentedString(userHiringDate)).append("\n");
    sb.append("    userDepartureDate: ").append(toIndentedString(userDepartureDate)).append("\n");
    sb.append("    appRole: ").append(toIndentedString(appRole)).append("\n");
    sb.append("    userDaysOffId: ").append(toIndentedString(userDaysOffId)).append("\n");
    sb.append("    tco: ").append(toIndentedString(tco)).append("\n");
    sb.append("    linkedUserRelation: ").append(toIndentedString(linkedUserRelation)).append("\n");
    sb.append("    deletedLinkedUserRelation: ").append(toIndentedString(deletedLinkedUserRelation)).append("\n");
    sb.append("    linkedManagerRelation: ").append(toIndentedString(linkedManagerRelation)).append("\n");
    sb.append("    deletedLinkedManagerRelation: ").append(toIndentedString(deletedLinkedManagerRelation)).append("\n");
    sb.append("    userWorkedHours: ").append(toIndentedString(userWorkedHours)).append("\n");
    sb.append("    userWorkContracts: ").append(toIndentedString(userWorkContracts)).append("\n");
    sb.append("    userLeaveVacationProfiles: ").append(toIndentedString(userLeaveVacationProfiles)).append("\n");
    sb.append("    userMaritalStatus: ").append(toIndentedString(userMaritalStatus)).append("\n");
    sb.append("    userLinkConnection: ").append(toIndentedString(userLinkConnection)).append("\n");
    sb.append("    userAddress: ").append(toIndentedString(userAddress)).append("\n");
    sb.append("    userPhones: ").append(toIndentedString(userPhones)).append("\n");
    sb.append("    userChildren: ").append(toIndentedString(userChildren)).append("\n");
    sb.append("    userCompanyOrganizations: ").append(toIndentedString(userCompanyOrganizations)).append("\n");
    sb.append("    userTokenDeviceConnections: ").append(toIndentedString(userTokenDeviceConnections)).append("\n");
    sb.append("    userWidgetsPref: ").append(toIndentedString(userWidgetsPref)).append("\n");
    sb.append("    userWellBeingVotes: ").append(toIndentedString(userWellBeingVotes)).append("\n");
    sb.append("    hasAccessToAzuneedPortal: ").append(toIndentedString(hasAccessToAzuneedPortal)).append("\n");
    sb.append("    userProducts: ").append(toIndentedString(userProducts)).append("\n");
    sb.append("    anAdmin: ").append(toIndentedString(anAdmin)).append("\n");
    sb.append("    idCompany: ").append(toIndentedString(idCompany)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

