/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UserWellBeingVoteId;


/**
 * UserWellBeingVoteItem
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:18:43.286+01:00")
public class UserWellBeingVoteItem   {
  @SerializedName("id")
  private UserWellBeingVoteId id = null;

  @SerializedName("companyDetail")
  private String companyDetail = null;

  @SerializedName("userName")
  private String userName = null;

  @SerializedName("userPhotoUrl")
  private String userPhotoUrl = null;

  @SerializedName("wellBeingLabel")
  private String wellBeingLabel = null;

  @SerializedName("wellBeingItemLabel")
  private String wellBeingItemLabel = null;

  @SerializedName("note")
  private Integer note = null;

  public UserWellBeingVoteItem id(UserWellBeingVoteId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserWellBeingVoteId getId() {
    return id;
  }

  public void setId(UserWellBeingVoteId id) {
    this.id = id;
  }

  public UserWellBeingVoteItem companyDetail(String companyDetail) {
    this.companyDetail = companyDetail;
    return this;
  }

   /**
   * Get companyDetail
   * @return companyDetail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCompanyDetail() {
    return companyDetail;
  }

  public void setCompanyDetail(String companyDetail) {
    this.companyDetail = companyDetail;
  }

  public UserWellBeingVoteItem userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public UserWellBeingVoteItem userPhotoUrl(String userPhotoUrl) {
    this.userPhotoUrl = userPhotoUrl;
    return this;
  }

   /**
   * Get userPhotoUrl
   * @return userPhotoUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserPhotoUrl() {
    return userPhotoUrl;
  }

  public void setUserPhotoUrl(String userPhotoUrl) {
    this.userPhotoUrl = userPhotoUrl;
  }

  public UserWellBeingVoteItem wellBeingLabel(String wellBeingLabel) {
    this.wellBeingLabel = wellBeingLabel;
    return this;
  }

   /**
   * Get wellBeingLabel
   * @return wellBeingLabel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWellBeingLabel() {
    return wellBeingLabel;
  }

  public void setWellBeingLabel(String wellBeingLabel) {
    this.wellBeingLabel = wellBeingLabel;
  }

  public UserWellBeingVoteItem wellBeingItemLabel(String wellBeingItemLabel) {
    this.wellBeingItemLabel = wellBeingItemLabel;
    return this;
  }

   /**
   * Get wellBeingItemLabel
   * @return wellBeingItemLabel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWellBeingItemLabel() {
    return wellBeingItemLabel;
  }

  public void setWellBeingItemLabel(String wellBeingItemLabel) {
    this.wellBeingItemLabel = wellBeingItemLabel;
  }

  public UserWellBeingVoteItem note(Integer note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNote() {
    return note;
  }

  public void setNote(Integer note) {
    this.note = note;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserWellBeingVoteItem userWellBeingVoteItem = (UserWellBeingVoteItem) o;
    return Objects.equals(this.id, userWellBeingVoteItem.id) &&
        Objects.equals(this.companyDetail, userWellBeingVoteItem.companyDetail) &&
        Objects.equals(this.userName, userWellBeingVoteItem.userName) &&
        Objects.equals(this.userPhotoUrl, userWellBeingVoteItem.userPhotoUrl) &&
        Objects.equals(this.wellBeingLabel, userWellBeingVoteItem.wellBeingLabel) &&
        Objects.equals(this.wellBeingItemLabel, userWellBeingVoteItem.wellBeingItemLabel) &&
        Objects.equals(this.note, userWellBeingVoteItem.note);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, companyDetail, userName, userPhotoUrl, wellBeingLabel, wellBeingItemLabel, note);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserWellBeingVoteItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    companyDetail: ").append(toIndentedString(companyDetail)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    userPhotoUrl: ").append(toIndentedString(userPhotoUrl)).append("\n");
    sb.append("    wellBeingLabel: ").append(toIndentedString(wellBeingLabel)).append("\n");
    sb.append("    wellBeingItemLabel: ").append(toIndentedString(wellBeingItemLabel)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

