/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UserAddressId;


/**
 * UserAddressItem
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:18:43.286+01:00")
public class UserAddressItem   {
  @SerializedName("id")
  private UserAddressId id = null;

  @SerializedName("addressType")
  private String addressType = null;

  @SerializedName("addressCountry")
  private String addressCountry = null;

  @SerializedName("addressCity")
  private String addressCity = null;

  @SerializedName("addressZipCode")
  private String addressZipCode = null;

  @SerializedName("addressDetail")
  private String addressDetail = null;

  @SerializedName("addressComment")
  private String addressComment = null;

  public UserAddressItem id(UserAddressId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserAddressId getId() {
    return id;
  }

  public void setId(UserAddressId id) {
    this.id = id;
  }

  public UserAddressItem addressType(String addressType) {
    this.addressType = addressType;
    return this;
  }

   /**
   * Get addressType
   * @return addressType
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getAddressType() {
    return addressType;
  }

  public void setAddressType(String addressType) {
    this.addressType = addressType;
  }

  public UserAddressItem addressCountry(String addressCountry) {
    this.addressCountry = addressCountry;
    return this;
  }

   /**
   * Get addressCountry
   * @return addressCountry
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getAddressCountry() {
    return addressCountry;
  }

  public void setAddressCountry(String addressCountry) {
    this.addressCountry = addressCountry;
  }

  public UserAddressItem addressCity(String addressCity) {
    this.addressCity = addressCity;
    return this;
  }

   /**
   * Get addressCity
   * @return addressCity
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getAddressCity() {
    return addressCity;
  }

  public void setAddressCity(String addressCity) {
    this.addressCity = addressCity;
  }

  public UserAddressItem addressZipCode(String addressZipCode) {
    this.addressZipCode = addressZipCode;
    return this;
  }

   /**
   * Get addressZipCode
   * @return addressZipCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAddressZipCode() {
    return addressZipCode;
  }

  public void setAddressZipCode(String addressZipCode) {
    this.addressZipCode = addressZipCode;
  }

  public UserAddressItem addressDetail(String addressDetail) {
    this.addressDetail = addressDetail;
    return this;
  }

   /**
   * Get addressDetail
   * @return addressDetail
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getAddressDetail() {
    return addressDetail;
  }

  public void setAddressDetail(String addressDetail) {
    this.addressDetail = addressDetail;
  }

  public UserAddressItem addressComment(String addressComment) {
    this.addressComment = addressComment;
    return this;
  }

   /**
   * Get addressComment
   * @return addressComment
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAddressComment() {
    return addressComment;
  }

  public void setAddressComment(String addressComment) {
    this.addressComment = addressComment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAddressItem userAddressItem = (UserAddressItem) o;
    return Objects.equals(this.id, userAddressItem.id) &&
        Objects.equals(this.addressType, userAddressItem.addressType) &&
        Objects.equals(this.addressCountry, userAddressItem.addressCountry) &&
        Objects.equals(this.addressCity, userAddressItem.addressCity) &&
        Objects.equals(this.addressZipCode, userAddressItem.addressZipCode) &&
        Objects.equals(this.addressDetail, userAddressItem.addressDetail) &&
        Objects.equals(this.addressComment, userAddressItem.addressComment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, addressType, addressCountry, addressCity, addressZipCode, addressDetail, addressComment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAddressItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    addressType: ").append(toIndentedString(addressType)).append("\n");
    sb.append("    addressCountry: ").append(toIndentedString(addressCountry)).append("\n");
    sb.append("    addressCity: ").append(toIndentedString(addressCity)).append("\n");
    sb.append("    addressZipCode: ").append(toIndentedString(addressZipCode)).append("\n");
    sb.append("    addressDetail: ").append(toIndentedString(addressDetail)).append("\n");
    sb.append("    addressComment: ").append(toIndentedString(addressComment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

