/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LeaveVacationProfileBeanId;
import io.swagger.client.model.UserLeaveVacationProfilesId;
import org.joda.time.DateTime;


/**
 * UserLeaveVacationProfiles
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:18:43.286+01:00")
public class UserLeaveVacationProfiles   {
  @SerializedName("id")
  private UserLeaveVacationProfilesId id = null;

  @SerializedName("leaveVacationProfileBeanId")
  private LeaveVacationProfileBeanId leaveVacationProfileBeanId = null;

  @SerializedName("leaveVacationProfileStartDate")
  private DateTime leaveVacationProfileStartDate = null;

  @SerializedName("leaveVacationProfileEndDate")
  private DateTime leaveVacationProfileEndDate = null;

  @SerializedName("earnRateMode")
  private String earnRateMode = null;

  public UserLeaveVacationProfiles id(UserLeaveVacationProfilesId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserLeaveVacationProfilesId getId() {
    return id;
  }

  public void setId(UserLeaveVacationProfilesId id) {
    this.id = id;
  }

  public UserLeaveVacationProfiles leaveVacationProfileBeanId(LeaveVacationProfileBeanId leaveVacationProfileBeanId) {
    this.leaveVacationProfileBeanId = leaveVacationProfileBeanId;
    return this;
  }

   /**
   * Get leaveVacationProfileBeanId
   * @return leaveVacationProfileBeanId
  **/
  @ApiModelProperty(example = "null", value = "")
  public LeaveVacationProfileBeanId getLeaveVacationProfileBeanId() {
    return leaveVacationProfileBeanId;
  }

  public void setLeaveVacationProfileBeanId(LeaveVacationProfileBeanId leaveVacationProfileBeanId) {
    this.leaveVacationProfileBeanId = leaveVacationProfileBeanId;
  }

  public UserLeaveVacationProfiles leaveVacationProfileStartDate(DateTime leaveVacationProfileStartDate) {
    this.leaveVacationProfileStartDate = leaveVacationProfileStartDate;
    return this;
  }

   /**
   * Get leaveVacationProfileStartDate
   * @return leaveVacationProfileStartDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getLeaveVacationProfileStartDate() {
    return leaveVacationProfileStartDate;
  }

  public void setLeaveVacationProfileStartDate(DateTime leaveVacationProfileStartDate) {
    this.leaveVacationProfileStartDate = leaveVacationProfileStartDate;
  }

  public UserLeaveVacationProfiles leaveVacationProfileEndDate(DateTime leaveVacationProfileEndDate) {
    this.leaveVacationProfileEndDate = leaveVacationProfileEndDate;
    return this;
  }

   /**
   * Get leaveVacationProfileEndDate
   * @return leaveVacationProfileEndDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getLeaveVacationProfileEndDate() {
    return leaveVacationProfileEndDate;
  }

  public void setLeaveVacationProfileEndDate(DateTime leaveVacationProfileEndDate) {
    this.leaveVacationProfileEndDate = leaveVacationProfileEndDate;
  }

  public UserLeaveVacationProfiles earnRateMode(String earnRateMode) {
    this.earnRateMode = earnRateMode;
    return this;
  }

   /**
   * Get earnRateMode
   * @return earnRateMode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEarnRateMode() {
    return earnRateMode;
  }

  public void setEarnRateMode(String earnRateMode) {
    this.earnRateMode = earnRateMode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserLeaveVacationProfiles userLeaveVacationProfiles = (UserLeaveVacationProfiles) o;
    return Objects.equals(this.id, userLeaveVacationProfiles.id) &&
        Objects.equals(this.leaveVacationProfileBeanId, userLeaveVacationProfiles.leaveVacationProfileBeanId) &&
        Objects.equals(this.leaveVacationProfileStartDate, userLeaveVacationProfiles.leaveVacationProfileStartDate) &&
        Objects.equals(this.leaveVacationProfileEndDate, userLeaveVacationProfiles.leaveVacationProfileEndDate) &&
        Objects.equals(this.earnRateMode, userLeaveVacationProfiles.earnRateMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, leaveVacationProfileBeanId, leaveVacationProfileStartDate, leaveVacationProfileEndDate, earnRateMode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserLeaveVacationProfiles {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    leaveVacationProfileBeanId: ").append(toIndentedString(leaveVacationProfileBeanId)).append("\n");
    sb.append("    leaveVacationProfileStartDate: ").append(toIndentedString(leaveVacationProfileStartDate)).append("\n");
    sb.append("    leaveVacationProfileEndDate: ").append(toIndentedString(leaveVacationProfileEndDate)).append("\n");
    sb.append("    earnRateMode: ").append(toIndentedString(earnRateMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

