/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UserChildrenId;
import org.joda.time.DateTime;


/**
 * UserChildren
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:24:13.221+01:00")
public class UserChildren   {
  @SerializedName("id")
  private UserChildrenId id = null;

  @SerializedName("childrenGender")
  private String childrenGender = null;

  @SerializedName("childrenFirstName")
  private String childrenFirstName = null;

  @SerializedName("childrenLastName")
  private String childrenLastName = null;

  @SerializedName("childrenBirthday")
  private DateTime childrenBirthday = null;

  public UserChildren id(UserChildrenId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserChildrenId getId() {
    return id;
  }

  public void setId(UserChildrenId id) {
    this.id = id;
  }

  public UserChildren childrenGender(String childrenGender) {
    this.childrenGender = childrenGender;
    return this;
  }

   /**
   * Get childrenGender
   * @return childrenGender
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getChildrenGender() {
    return childrenGender;
  }

  public void setChildrenGender(String childrenGender) {
    this.childrenGender = childrenGender;
  }

  public UserChildren childrenFirstName(String childrenFirstName) {
    this.childrenFirstName = childrenFirstName;
    return this;
  }

   /**
   * Get childrenFirstName
   * @return childrenFirstName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getChildrenFirstName() {
    return childrenFirstName;
  }

  public void setChildrenFirstName(String childrenFirstName) {
    this.childrenFirstName = childrenFirstName;
  }

  public UserChildren childrenLastName(String childrenLastName) {
    this.childrenLastName = childrenLastName;
    return this;
  }

   /**
   * Get childrenLastName
   * @return childrenLastName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getChildrenLastName() {
    return childrenLastName;
  }

  public void setChildrenLastName(String childrenLastName) {
    this.childrenLastName = childrenLastName;
  }

  public UserChildren childrenBirthday(DateTime childrenBirthday) {
    this.childrenBirthday = childrenBirthday;
    return this;
  }

   /**
   * Get childrenBirthday
   * @return childrenBirthday
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getChildrenBirthday() {
    return childrenBirthday;
  }

  public void setChildrenBirthday(DateTime childrenBirthday) {
    this.childrenBirthday = childrenBirthday;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserChildren userChildren = (UserChildren) o;
    return Objects.equals(this.id, userChildren.id) &&
        Objects.equals(this.childrenGender, userChildren.childrenGender) &&
        Objects.equals(this.childrenFirstName, userChildren.childrenFirstName) &&
        Objects.equals(this.childrenLastName, userChildren.childrenLastName) &&
        Objects.equals(this.childrenBirthday, userChildren.childrenBirthday);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, childrenGender, childrenFirstName, childrenLastName, childrenBirthday);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserChildren {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    childrenGender: ").append(toIndentedString(childrenGender)).append("\n");
    sb.append("    childrenFirstName: ").append(toIndentedString(childrenFirstName)).append("\n");
    sb.append("    childrenLastName: ").append(toIndentedString(childrenLastName)).append("\n");
    sb.append("    childrenBirthday: ").append(toIndentedString(childrenBirthday)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

