/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * UserCompanyOrganizationId
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:24:13.221+01:00")
public class UserCompanyOrganizationId   {
  @SerializedName("stringOf")
  private String stringOf = null;

  @SerializedName("idUser")
  private String idUser = null;

  @SerializedName("idCompany")
  private String idCompany = null;

  @SerializedName("idCompanyOrg")
  private String idCompanyOrg = null;

  @SerializedName("idTreeBeanOrg")
  private String idTreeBeanOrg = null;

  @SerializedName("idTreeBeanOrgItem")
  private String idTreeBeanOrgItem = null;

  public UserCompanyOrganizationId stringOf(String stringOf) {
    this.stringOf = stringOf;
    return this;
  }

   /**
   * Get stringOf
   * @return stringOf
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStringOf() {
    return stringOf;
  }

  public void setStringOf(String stringOf) {
    this.stringOf = stringOf;
  }

  public UserCompanyOrganizationId idUser(String idUser) {
    this.idUser = idUser;
    return this;
  }

   /**
   * Get idUser
   * @return idUser
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdUser() {
    return idUser;
  }

  public void setIdUser(String idUser) {
    this.idUser = idUser;
  }

  public UserCompanyOrganizationId idCompany(String idCompany) {
    this.idCompany = idCompany;
    return this;
  }

   /**
   * Get idCompany
   * @return idCompany
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdCompany() {
    return idCompany;
  }

  public void setIdCompany(String idCompany) {
    this.idCompany = idCompany;
  }

  public UserCompanyOrganizationId idCompanyOrg(String idCompanyOrg) {
    this.idCompanyOrg = idCompanyOrg;
    return this;
  }

   /**
   * Get idCompanyOrg
   * @return idCompanyOrg
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdCompanyOrg() {
    return idCompanyOrg;
  }

  public void setIdCompanyOrg(String idCompanyOrg) {
    this.idCompanyOrg = idCompanyOrg;
  }

  public UserCompanyOrganizationId idTreeBeanOrg(String idTreeBeanOrg) {
    this.idTreeBeanOrg = idTreeBeanOrg;
    return this;
  }

   /**
   * Get idTreeBeanOrg
   * @return idTreeBeanOrg
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdTreeBeanOrg() {
    return idTreeBeanOrg;
  }

  public void setIdTreeBeanOrg(String idTreeBeanOrg) {
    this.idTreeBeanOrg = idTreeBeanOrg;
  }

  public UserCompanyOrganizationId idTreeBeanOrgItem(String idTreeBeanOrgItem) {
    this.idTreeBeanOrgItem = idTreeBeanOrgItem;
    return this;
  }

   /**
   * Get idTreeBeanOrgItem
   * @return idTreeBeanOrgItem
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdTreeBeanOrgItem() {
    return idTreeBeanOrgItem;
  }

  public void setIdTreeBeanOrgItem(String idTreeBeanOrgItem) {
    this.idTreeBeanOrgItem = idTreeBeanOrgItem;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserCompanyOrganizationId userCompanyOrganizationId = (UserCompanyOrganizationId) o;
    return Objects.equals(this.stringOf, userCompanyOrganizationId.stringOf) &&
        Objects.equals(this.idUser, userCompanyOrganizationId.idUser) &&
        Objects.equals(this.idCompany, userCompanyOrganizationId.idCompany) &&
        Objects.equals(this.idCompanyOrg, userCompanyOrganizationId.idCompanyOrg) &&
        Objects.equals(this.idTreeBeanOrg, userCompanyOrganizationId.idTreeBeanOrg) &&
        Objects.equals(this.idTreeBeanOrgItem, userCompanyOrganizationId.idTreeBeanOrgItem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stringOf, idUser, idCompany, idCompanyOrg, idTreeBeanOrg, idTreeBeanOrgItem);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserCompanyOrganizationId {\n");
    
    sb.append("    stringOf: ").append(toIndentedString(stringOf)).append("\n");
    sb.append("    idUser: ").append(toIndentedString(idUser)).append("\n");
    sb.append("    idCompany: ").append(toIndentedString(idCompany)).append("\n");
    sb.append("    idCompanyOrg: ").append(toIndentedString(idCompanyOrg)).append("\n");
    sb.append("    idTreeBeanOrg: ").append(toIndentedString(idTreeBeanOrg)).append("\n");
    sb.append("    idTreeBeanOrgItem: ").append(toIndentedString(idTreeBeanOrgItem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

