/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.HourProfileId;
import io.swagger.client.model.UserWorkedHoursId;
import org.joda.time.DateTime;


/**
 * UserWorkedHours
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:24:13.221+01:00")
public class UserWorkedHours   {
  @SerializedName("id")
  private UserWorkedHoursId id = null;

  @SerializedName("hourProfileId")
  private HourProfileId hourProfileId = null;

  @SerializedName("workedHoursStartDate")
  private DateTime workedHoursStartDate = null;

  @SerializedName("workedHoursEndDate")
  private DateTime workedHoursEndDate = null;

  @SerializedName("workedHoursRateActivity")
  private Integer workedHoursRateActivity = null;

  public UserWorkedHours id(UserWorkedHoursId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserWorkedHoursId getId() {
    return id;
  }

  public void setId(UserWorkedHoursId id) {
    this.id = id;
  }

  public UserWorkedHours hourProfileId(HourProfileId hourProfileId) {
    this.hourProfileId = hourProfileId;
    return this;
  }

   /**
   * Get hourProfileId
   * @return hourProfileId
  **/
  @ApiModelProperty(example = "null", value = "")
  public HourProfileId getHourProfileId() {
    return hourProfileId;
  }

  public void setHourProfileId(HourProfileId hourProfileId) {
    this.hourProfileId = hourProfileId;
  }

  public UserWorkedHours workedHoursStartDate(DateTime workedHoursStartDate) {
    this.workedHoursStartDate = workedHoursStartDate;
    return this;
  }

   /**
   * Get workedHoursStartDate
   * @return workedHoursStartDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getWorkedHoursStartDate() {
    return workedHoursStartDate;
  }

  public void setWorkedHoursStartDate(DateTime workedHoursStartDate) {
    this.workedHoursStartDate = workedHoursStartDate;
  }

  public UserWorkedHours workedHoursEndDate(DateTime workedHoursEndDate) {
    this.workedHoursEndDate = workedHoursEndDate;
    return this;
  }

   /**
   * Get workedHoursEndDate
   * @return workedHoursEndDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getWorkedHoursEndDate() {
    return workedHoursEndDate;
  }

  public void setWorkedHoursEndDate(DateTime workedHoursEndDate) {
    this.workedHoursEndDate = workedHoursEndDate;
  }

  public UserWorkedHours workedHoursRateActivity(Integer workedHoursRateActivity) {
    this.workedHoursRateActivity = workedHoursRateActivity;
    return this;
  }

   /**
   * Get workedHoursRateActivity
   * @return workedHoursRateActivity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWorkedHoursRateActivity() {
    return workedHoursRateActivity;
  }

  public void setWorkedHoursRateActivity(Integer workedHoursRateActivity) {
    this.workedHoursRateActivity = workedHoursRateActivity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserWorkedHours userWorkedHours = (UserWorkedHours) o;
    return Objects.equals(this.id, userWorkedHours.id) &&
        Objects.equals(this.hourProfileId, userWorkedHours.hourProfileId) &&
        Objects.equals(this.workedHoursStartDate, userWorkedHours.workedHoursStartDate) &&
        Objects.equals(this.workedHoursEndDate, userWorkedHours.workedHoursEndDate) &&
        Objects.equals(this.workedHoursRateActivity, userWorkedHours.workedHoursRateActivity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, hourProfileId, workedHoursStartDate, workedHoursEndDate, workedHoursRateActivity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserWorkedHours {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    hourProfileId: ").append(toIndentedString(hourProfileId)).append("\n");
    sb.append("    workedHoursStartDate: ").append(toIndentedString(workedHoursStartDate)).append("\n");
    sb.append("    workedHoursEndDate: ").append(toIndentedString(workedHoursEndDate)).append("\n");
    sb.append("    workedHoursRateActivity: ").append(toIndentedString(workedHoursRateActivity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

