/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UserWorkContractsId;
import org.joda.time.DateTime;


/**
 * UserWorkContracts
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:24:13.221+01:00")
public class UserWorkContracts   {
  @SerializedName("id")
  private UserWorkContractsId id = null;

  @SerializedName("workContractCategory")
  private String workContractCategory = null;

  @SerializedName("workContractStartDate")
  private DateTime workContractStartDate = null;

  @SerializedName("workContractEndDate")
  private DateTime workContractEndDate = null;

  @SerializedName("workContractEndReason")
  private String workContractEndReason = null;

  @SerializedName("workContractComment")
  private String workContractComment = null;

  public UserWorkContracts id(UserWorkContractsId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserWorkContractsId getId() {
    return id;
  }

  public void setId(UserWorkContractsId id) {
    this.id = id;
  }

  public UserWorkContracts workContractCategory(String workContractCategory) {
    this.workContractCategory = workContractCategory;
    return this;
  }

   /**
   * Get workContractCategory
   * @return workContractCategory
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWorkContractCategory() {
    return workContractCategory;
  }

  public void setWorkContractCategory(String workContractCategory) {
    this.workContractCategory = workContractCategory;
  }

  public UserWorkContracts workContractStartDate(DateTime workContractStartDate) {
    this.workContractStartDate = workContractStartDate;
    return this;
  }

   /**
   * Get workContractStartDate
   * @return workContractStartDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getWorkContractStartDate() {
    return workContractStartDate;
  }

  public void setWorkContractStartDate(DateTime workContractStartDate) {
    this.workContractStartDate = workContractStartDate;
  }

  public UserWorkContracts workContractEndDate(DateTime workContractEndDate) {
    this.workContractEndDate = workContractEndDate;
    return this;
  }

   /**
   * Get workContractEndDate
   * @return workContractEndDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getWorkContractEndDate() {
    return workContractEndDate;
  }

  public void setWorkContractEndDate(DateTime workContractEndDate) {
    this.workContractEndDate = workContractEndDate;
  }

  public UserWorkContracts workContractEndReason(String workContractEndReason) {
    this.workContractEndReason = workContractEndReason;
    return this;
  }

   /**
   * Get workContractEndReason
   * @return workContractEndReason
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWorkContractEndReason() {
    return workContractEndReason;
  }

  public void setWorkContractEndReason(String workContractEndReason) {
    this.workContractEndReason = workContractEndReason;
  }

  public UserWorkContracts workContractComment(String workContractComment) {
    this.workContractComment = workContractComment;
    return this;
  }

   /**
   * Get workContractComment
   * @return workContractComment
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWorkContractComment() {
    return workContractComment;
  }

  public void setWorkContractComment(String workContractComment) {
    this.workContractComment = workContractComment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserWorkContracts userWorkContracts = (UserWorkContracts) o;
    return Objects.equals(this.id, userWorkContracts.id) &&
        Objects.equals(this.workContractCategory, userWorkContracts.workContractCategory) &&
        Objects.equals(this.workContractStartDate, userWorkContracts.workContractStartDate) &&
        Objects.equals(this.workContractEndDate, userWorkContracts.workContractEndDate) &&
        Objects.equals(this.workContractEndReason, userWorkContracts.workContractEndReason) &&
        Objects.equals(this.workContractComment, userWorkContracts.workContractComment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, workContractCategory, workContractStartDate, workContractEndDate, workContractEndReason, workContractComment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserWorkContracts {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    workContractCategory: ").append(toIndentedString(workContractCategory)).append("\n");
    sb.append("    workContractStartDate: ").append(toIndentedString(workContractStartDate)).append("\n");
    sb.append("    workContractEndDate: ").append(toIndentedString(workContractEndDate)).append("\n");
    sb.append("    workContractEndReason: ").append(toIndentedString(workContractEndReason)).append("\n");
    sb.append("    workContractComment: ").append(toIndentedString(workContractComment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

