/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.LocalDate;


/**
 * UserWellBeingVoteId
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:18:43.286+01:00")
public class UserWellBeingVoteId   {
  @SerializedName("stringOf")
  private String stringOf = null;

  @SerializedName("idUser")
  private String idUser = null;

  @SerializedName("idCompany")
  private String idCompany = null;

  @SerializedName("idCompanyWellBeing")
  private String idCompanyWellBeing = null;

  @SerializedName("idWellBeing")
  private String idWellBeing = null;

  @SerializedName("idWellBeingItem")
  private String idWellBeingItem = null;

  @SerializedName("voteDate")
  private LocalDate voteDate = null;

  public UserWellBeingVoteId stringOf(String stringOf) {
    this.stringOf = stringOf;
    return this;
  }

   /**
   * Get stringOf
   * @return stringOf
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStringOf() {
    return stringOf;
  }

  public void setStringOf(String stringOf) {
    this.stringOf = stringOf;
  }

  public UserWellBeingVoteId idUser(String idUser) {
    this.idUser = idUser;
    return this;
  }

   /**
   * Get idUser
   * @return idUser
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdUser() {
    return idUser;
  }

  public void setIdUser(String idUser) {
    this.idUser = idUser;
  }

  public UserWellBeingVoteId idCompany(String idCompany) {
    this.idCompany = idCompany;
    return this;
  }

   /**
   * Get idCompany
   * @return idCompany
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdCompany() {
    return idCompany;
  }

  public void setIdCompany(String idCompany) {
    this.idCompany = idCompany;
  }

  public UserWellBeingVoteId idCompanyWellBeing(String idCompanyWellBeing) {
    this.idCompanyWellBeing = idCompanyWellBeing;
    return this;
  }

   /**
   * Get idCompanyWellBeing
   * @return idCompanyWellBeing
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdCompanyWellBeing() {
    return idCompanyWellBeing;
  }

  public void setIdCompanyWellBeing(String idCompanyWellBeing) {
    this.idCompanyWellBeing = idCompanyWellBeing;
  }

  public UserWellBeingVoteId idWellBeing(String idWellBeing) {
    this.idWellBeing = idWellBeing;
    return this;
  }

   /**
   * Get idWellBeing
   * @return idWellBeing
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdWellBeing() {
    return idWellBeing;
  }

  public void setIdWellBeing(String idWellBeing) {
    this.idWellBeing = idWellBeing;
  }

  public UserWellBeingVoteId idWellBeingItem(String idWellBeingItem) {
    this.idWellBeingItem = idWellBeingItem;
    return this;
  }

   /**
   * Get idWellBeingItem
   * @return idWellBeingItem
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdWellBeingItem() {
    return idWellBeingItem;
  }

  public void setIdWellBeingItem(String idWellBeingItem) {
    this.idWellBeingItem = idWellBeingItem;
  }

  public UserWellBeingVoteId voteDate(LocalDate voteDate) {
    this.voteDate = voteDate;
    return this;
  }

   /**
   * Get voteDate
   * @return voteDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getVoteDate() {
    return voteDate;
  }

  public void setVoteDate(LocalDate voteDate) {
    this.voteDate = voteDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserWellBeingVoteId userWellBeingVoteId = (UserWellBeingVoteId) o;
    return Objects.equals(this.stringOf, userWellBeingVoteId.stringOf) &&
        Objects.equals(this.idUser, userWellBeingVoteId.idUser) &&
        Objects.equals(this.idCompany, userWellBeingVoteId.idCompany) &&
        Objects.equals(this.idCompanyWellBeing, userWellBeingVoteId.idCompanyWellBeing) &&
        Objects.equals(this.idWellBeing, userWellBeingVoteId.idWellBeing) &&
        Objects.equals(this.idWellBeingItem, userWellBeingVoteId.idWellBeingItem) &&
        Objects.equals(this.voteDate, userWellBeingVoteId.voteDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stringOf, idUser, idCompany, idCompanyWellBeing, idWellBeing, idWellBeingItem, voteDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserWellBeingVoteId {\n");
    
    sb.append("    stringOf: ").append(toIndentedString(stringOf)).append("\n");
    sb.append("    idUser: ").append(toIndentedString(idUser)).append("\n");
    sb.append("    idCompany: ").append(toIndentedString(idCompany)).append("\n");
    sb.append("    idCompanyWellBeing: ").append(toIndentedString(idCompanyWellBeing)).append("\n");
    sb.append("    idWellBeing: ").append(toIndentedString(idWellBeing)).append("\n");
    sb.append("    idWellBeingItem: ").append(toIndentedString(idWellBeingItem)).append("\n");
    sb.append("    voteDate: ").append(toIndentedString(voteDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

