/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DaysOffBeanId;
import io.swagger.client.model.FileBean;
import io.swagger.client.model.GlobalControler;
import io.swagger.client.model.LinkedManagerRelation;
import io.swagger.client.model.LinkedUserRelation;
import io.swagger.client.model.UserAddress;
import io.swagger.client.model.UserChildren;
import io.swagger.client.model.UserCompanyOrganization;
import io.swagger.client.model.UserLeaveVacationProfiles;
import io.swagger.client.model.UserPhones;
import io.swagger.client.model.UserProduct;
import io.swagger.client.model.UserProfileId;
import io.swagger.client.model.UserTokenDeviceConnection;
import io.swagger.client.model.UserWellBeingVote;
import io.swagger.client.model.UserWidgetsPref;
import io.swagger.client.model.UserWorkContracts;
import io.swagger.client.model.UserWorkedHours;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * UserBean
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:18:43.286+01:00")
public class UserBean   {
  @SerializedName("userCreate")
  private String userCreate = null;

  @SerializedName("dateCreate")
  private DateTime dateCreate = null;

  @SerializedName("userUpdate")
  private String userUpdate = null;

  @SerializedName("dateUpdate")
  private DateTime dateUpdate = null;

  @SerializedName("internalCode")
  private String internalCode = null;

  @SerializedName("id")
  private Object id = null;

  @SerializedName("userGender")
  private String userGender = null;

  @SerializedName("userFirstName")
  private String userFirstName = null;

  @SerializedName("userLastName")
  private String userLastName = null;

  @SerializedName("userEmail")
  private String userEmail = null;

  @SerializedName("userEmailTempKey")
  private String userEmailTempKey = null;

  @SerializedName("userSerial")
  private String userSerial = null;

  @SerializedName("userPwd")
  private String userPwd = null;

  @SerializedName("userLocale")
  private String userLocale = null;

  @SerializedName("userProfileId")
  private UserProfileId userProfileId = null;

  @SerializedName("userPhoto")
  private FileBean userPhoto = null;

  @SerializedName("userFunction")
  private String userFunction = null;

  @SerializedName("userBirthDay")
  private DateTime userBirthDay = null;

  @SerializedName("userMaritalStatus")
  private String userMaritalStatus = null;

  @SerializedName("isAnAdmin")
  private Boolean isAnAdmin = false;

  @SerializedName("userPayroll")
  private Double userPayroll = null;

  @SerializedName("userWorkCategory")
  private String userWorkCategory = null;

  @SerializedName("userWorkLevel")
  private String userWorkLevel = null;

  @SerializedName("userEchelon")
  private String userEchelon = null;

  @SerializedName("userTimeZone")
  private String userTimeZone = null;

  @SerializedName("appRole")
  private String appRole = null;

  @SerializedName("userHiringDate")
  private DateTime userHiringDate = null;

  @SerializedName("userDepartureDate")
  private DateTime userDepartureDate = null;

  @SerializedName("userDaysOffId")
  private DaysOffBeanId userDaysOffId = null;

  @SerializedName("hasAccessToAzuneedPortal")
  private Boolean hasAccessToAzuneedPortal = false;

  @SerializedName("tco")
  private Double tco = null;

  @SerializedName("linkedUserRelation")
  private List<LinkedUserRelation> linkedUserRelation = new ArrayList<LinkedUserRelation>();

  @SerializedName("linkedManagerRelation")
  private List<LinkedManagerRelation> linkedManagerRelation = new ArrayList<LinkedManagerRelation>();

  @SerializedName("userWorkedHours")
  private List<UserWorkedHours> userWorkedHours = new ArrayList<UserWorkedHours>();

  @SerializedName("userWorkContracts")
  private List<UserWorkContracts> userWorkContracts = new ArrayList<UserWorkContracts>();

  @SerializedName("userLeaveVacationProfiles")
  private List<UserLeaveVacationProfiles> userLeaveVacationProfiles = new ArrayList<UserLeaveVacationProfiles>();

  @SerializedName("userAddress")
  private List<UserAddress> userAddress = new ArrayList<UserAddress>();

  @SerializedName("userPhones")
  private List<UserPhones> userPhones = new ArrayList<UserPhones>();

  @SerializedName("userChildren")
  private List<UserChildren> userChildren = new ArrayList<UserChildren>();

  @SerializedName("userCompanyOrganizations")
  private List<UserCompanyOrganization> userCompanyOrganizations = new ArrayList<UserCompanyOrganization>();

  @SerializedName("userTokenDeviceConnections")
  private List<UserTokenDeviceConnection> userTokenDeviceConnections = new ArrayList<UserTokenDeviceConnection>();

  @SerializedName("userWidgetsPref")
  private List<UserWidgetsPref> userWidgetsPref = new ArrayList<UserWidgetsPref>();

  @SerializedName("userWellBeingVotes")
  private List<UserWellBeingVote> userWellBeingVotes = new ArrayList<UserWellBeingVote>();

  @SerializedName("userProducts")
  private List<UserProduct> userProducts = new ArrayList<UserProduct>();

  @SerializedName("userInformation")
  private String userInformation = null;

  @SerializedName("idCompany")
  private String idCompany = null;

  @SerializedName("idUser")
  private String idUser = null;

  @SerializedName("controllerInstance")
  private GlobalControler controllerInstance = null;

  public UserBean userCreate(String userCreate) {
    this.userCreate = userCreate;
    return this;
  }

   /**
   * Get userCreate
   * @return userCreate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserCreate() {
    return userCreate;
  }

  public void setUserCreate(String userCreate) {
    this.userCreate = userCreate;
  }

  public UserBean dateCreate(DateTime dateCreate) {
    this.dateCreate = dateCreate;
    return this;
  }

   /**
   * Get dateCreate
   * @return dateCreate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateCreate() {
    return dateCreate;
  }

  public void setDateCreate(DateTime dateCreate) {
    this.dateCreate = dateCreate;
  }

  public UserBean userUpdate(String userUpdate) {
    this.userUpdate = userUpdate;
    return this;
  }

   /**
   * Get userUpdate
   * @return userUpdate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserUpdate() {
    return userUpdate;
  }

  public void setUserUpdate(String userUpdate) {
    this.userUpdate = userUpdate;
  }

  public UserBean dateUpdate(DateTime dateUpdate) {
    this.dateUpdate = dateUpdate;
    return this;
  }

   /**
   * Get dateUpdate
   * @return dateUpdate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateUpdate() {
    return dateUpdate;
  }

  public void setDateUpdate(DateTime dateUpdate) {
    this.dateUpdate = dateUpdate;
  }

  public UserBean internalCode(String internalCode) {
    this.internalCode = internalCode;
    return this;
  }

   /**
   * Get internalCode
   * @return internalCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInternalCode() {
    return internalCode;
  }

  public void setInternalCode(String internalCode) {
    this.internalCode = internalCode;
  }

  public UserBean id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public UserBean userGender(String userGender) {
    this.userGender = userGender;
    return this;
  }

   /**
   * Get userGender
   * @return userGender
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserGender() {
    return userGender;
  }

  public void setUserGender(String userGender) {
    this.userGender = userGender;
  }

  public UserBean userFirstName(String userFirstName) {
    this.userFirstName = userFirstName;
    return this;
  }

   /**
   * Get userFirstName
   * @return userFirstName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserFirstName() {
    return userFirstName;
  }

  public void setUserFirstName(String userFirstName) {
    this.userFirstName = userFirstName;
  }

  public UserBean userLastName(String userLastName) {
    this.userLastName = userLastName;
    return this;
  }

   /**
   * Get userLastName
   * @return userLastName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserLastName() {
    return userLastName;
  }

  public void setUserLastName(String userLastName) {
    this.userLastName = userLastName;
  }

  public UserBean userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

   /**
   * Get userEmail
   * @return userEmail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public UserBean userEmailTempKey(String userEmailTempKey) {
    this.userEmailTempKey = userEmailTempKey;
    return this;
  }

   /**
   * Get userEmailTempKey
   * @return userEmailTempKey
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserEmailTempKey() {
    return userEmailTempKey;
  }

  public void setUserEmailTempKey(String userEmailTempKey) {
    this.userEmailTempKey = userEmailTempKey;
  }

  public UserBean userSerial(String userSerial) {
    this.userSerial = userSerial;
    return this;
  }

   /**
   * Get userSerial
   * @return userSerial
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserSerial() {
    return userSerial;
  }

  public void setUserSerial(String userSerial) {
    this.userSerial = userSerial;
  }

  public UserBean userPwd(String userPwd) {
    this.userPwd = userPwd;
    return this;
  }

   /**
   * Get userPwd
   * @return userPwd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserPwd() {
    return userPwd;
  }

  public void setUserPwd(String userPwd) {
    this.userPwd = userPwd;
  }

  public UserBean userLocale(String userLocale) {
    this.userLocale = userLocale;
    return this;
  }

   /**
   * Get userLocale
   * @return userLocale
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserLocale() {
    return userLocale;
  }

  public void setUserLocale(String userLocale) {
    this.userLocale = userLocale;
  }

  public UserBean userProfileId(UserProfileId userProfileId) {
    this.userProfileId = userProfileId;
    return this;
  }

   /**
   * Get userProfileId
   * @return userProfileId
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserProfileId getUserProfileId() {
    return userProfileId;
  }

  public void setUserProfileId(UserProfileId userProfileId) {
    this.userProfileId = userProfileId;
  }

  public UserBean userPhoto(FileBean userPhoto) {
    this.userPhoto = userPhoto;
    return this;
  }

   /**
   * Get userPhoto
   * @return userPhoto
  **/
  @ApiModelProperty(example = "null", value = "")
  public FileBean getUserPhoto() {
    return userPhoto;
  }

  public void setUserPhoto(FileBean userPhoto) {
    this.userPhoto = userPhoto;
  }

  public UserBean userFunction(String userFunction) {
    this.userFunction = userFunction;
    return this;
  }

   /**
   * Get userFunction
   * @return userFunction
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserFunction() {
    return userFunction;
  }

  public void setUserFunction(String userFunction) {
    this.userFunction = userFunction;
  }

  public UserBean userBirthDay(DateTime userBirthDay) {
    this.userBirthDay = userBirthDay;
    return this;
  }

   /**
   * Get userBirthDay
   * @return userBirthDay
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getUserBirthDay() {
    return userBirthDay;
  }

  public void setUserBirthDay(DateTime userBirthDay) {
    this.userBirthDay = userBirthDay;
  }

  public UserBean userMaritalStatus(String userMaritalStatus) {
    this.userMaritalStatus = userMaritalStatus;
    return this;
  }

   /**
   * Get userMaritalStatus
   * @return userMaritalStatus
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserMaritalStatus() {
    return userMaritalStatus;
  }

  public void setUserMaritalStatus(String userMaritalStatus) {
    this.userMaritalStatus = userMaritalStatus;
  }

  public UserBean isAnAdmin(Boolean isAnAdmin) {
    this.isAnAdmin = isAnAdmin;
    return this;
  }

   /**
   * Get isAnAdmin
   * @return isAnAdmin
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsAnAdmin() {
    return isAnAdmin;
  }

  public void setIsAnAdmin(Boolean isAnAdmin) {
    this.isAnAdmin = isAnAdmin;
  }

  public UserBean userPayroll(Double userPayroll) {
    this.userPayroll = userPayroll;
    return this;
  }

   /**
   * Get userPayroll
   * @return userPayroll
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getUserPayroll() {
    return userPayroll;
  }

  public void setUserPayroll(Double userPayroll) {
    this.userPayroll = userPayroll;
  }

  public UserBean userWorkCategory(String userWorkCategory) {
    this.userWorkCategory = userWorkCategory;
    return this;
  }

   /**
   * Get userWorkCategory
   * @return userWorkCategory
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserWorkCategory() {
    return userWorkCategory;
  }

  public void setUserWorkCategory(String userWorkCategory) {
    this.userWorkCategory = userWorkCategory;
  }

  public UserBean userWorkLevel(String userWorkLevel) {
    this.userWorkLevel = userWorkLevel;
    return this;
  }

   /**
   * Get userWorkLevel
   * @return userWorkLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserWorkLevel() {
    return userWorkLevel;
  }

  public void setUserWorkLevel(String userWorkLevel) {
    this.userWorkLevel = userWorkLevel;
  }

  public UserBean userEchelon(String userEchelon) {
    this.userEchelon = userEchelon;
    return this;
  }

   /**
   * Get userEchelon
   * @return userEchelon
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserEchelon() {
    return userEchelon;
  }

  public void setUserEchelon(String userEchelon) {
    this.userEchelon = userEchelon;
  }

  public UserBean userTimeZone(String userTimeZone) {
    this.userTimeZone = userTimeZone;
    return this;
  }

   /**
   * Get userTimeZone
   * @return userTimeZone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserTimeZone() {
    return userTimeZone;
  }

  public void setUserTimeZone(String userTimeZone) {
    this.userTimeZone = userTimeZone;
  }

  public UserBean appRole(String appRole) {
    this.appRole = appRole;
    return this;
  }

   /**
   * Get appRole
   * @return appRole
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAppRole() {
    return appRole;
  }

  public void setAppRole(String appRole) {
    this.appRole = appRole;
  }

  public UserBean userHiringDate(DateTime userHiringDate) {
    this.userHiringDate = userHiringDate;
    return this;
  }

   /**
   * Get userHiringDate
   * @return userHiringDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getUserHiringDate() {
    return userHiringDate;
  }

  public void setUserHiringDate(DateTime userHiringDate) {
    this.userHiringDate = userHiringDate;
  }

  public UserBean userDepartureDate(DateTime userDepartureDate) {
    this.userDepartureDate = userDepartureDate;
    return this;
  }

   /**
   * Get userDepartureDate
   * @return userDepartureDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getUserDepartureDate() {
    return userDepartureDate;
  }

  public void setUserDepartureDate(DateTime userDepartureDate) {
    this.userDepartureDate = userDepartureDate;
  }

  public UserBean userDaysOffId(DaysOffBeanId userDaysOffId) {
    this.userDaysOffId = userDaysOffId;
    return this;
  }

   /**
   * Get userDaysOffId
   * @return userDaysOffId
  **/
  @ApiModelProperty(example = "null", value = "")
  public DaysOffBeanId getUserDaysOffId() {
    return userDaysOffId;
  }

  public void setUserDaysOffId(DaysOffBeanId userDaysOffId) {
    this.userDaysOffId = userDaysOffId;
  }

  public UserBean hasAccessToAzuneedPortal(Boolean hasAccessToAzuneedPortal) {
    this.hasAccessToAzuneedPortal = hasAccessToAzuneedPortal;
    return this;
  }

   /**
   * Get hasAccessToAzuneedPortal
   * @return hasAccessToAzuneedPortal
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getHasAccessToAzuneedPortal() {
    return hasAccessToAzuneedPortal;
  }

  public void setHasAccessToAzuneedPortal(Boolean hasAccessToAzuneedPortal) {
    this.hasAccessToAzuneedPortal = hasAccessToAzuneedPortal;
  }

  public UserBean tco(Double tco) {
    this.tco = tco;
    return this;
  }

   /**
   * Get tco
   * @return tco
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTco() {
    return tco;
  }

  public void setTco(Double tco) {
    this.tco = tco;
  }

  public UserBean linkedUserRelation(List<LinkedUserRelation> linkedUserRelation) {
    this.linkedUserRelation = linkedUserRelation;
    return this;
  }

  public UserBean addLinkedUserRelationItem(LinkedUserRelation linkedUserRelationItem) {
    this.linkedUserRelation.add(linkedUserRelationItem);
    return this;
  }

   /**
   * Get linkedUserRelation
   * @return linkedUserRelation
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LinkedUserRelation> getLinkedUserRelation() {
    return linkedUserRelation;
  }

  public void setLinkedUserRelation(List<LinkedUserRelation> linkedUserRelation) {
    this.linkedUserRelation = linkedUserRelation;
  }

  public UserBean linkedManagerRelation(List<LinkedManagerRelation> linkedManagerRelation) {
    this.linkedManagerRelation = linkedManagerRelation;
    return this;
  }

  public UserBean addLinkedManagerRelationItem(LinkedManagerRelation linkedManagerRelationItem) {
    this.linkedManagerRelation.add(linkedManagerRelationItem);
    return this;
  }

   /**
   * Get linkedManagerRelation
   * @return linkedManagerRelation
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LinkedManagerRelation> getLinkedManagerRelation() {
    return linkedManagerRelation;
  }

  public void setLinkedManagerRelation(List<LinkedManagerRelation> linkedManagerRelation) {
    this.linkedManagerRelation = linkedManagerRelation;
  }

  public UserBean userWorkedHours(List<UserWorkedHours> userWorkedHours) {
    this.userWorkedHours = userWorkedHours;
    return this;
  }

  public UserBean addUserWorkedHoursItem(UserWorkedHours userWorkedHoursItem) {
    this.userWorkedHours.add(userWorkedHoursItem);
    return this;
  }

   /**
   * Get userWorkedHours
   * @return userWorkedHours
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserWorkedHours> getUserWorkedHours() {
    return userWorkedHours;
  }

  public void setUserWorkedHours(List<UserWorkedHours> userWorkedHours) {
    this.userWorkedHours = userWorkedHours;
  }

  public UserBean userWorkContracts(List<UserWorkContracts> userWorkContracts) {
    this.userWorkContracts = userWorkContracts;
    return this;
  }

  public UserBean addUserWorkContractsItem(UserWorkContracts userWorkContractsItem) {
    this.userWorkContracts.add(userWorkContractsItem);
    return this;
  }

   /**
   * Get userWorkContracts
   * @return userWorkContracts
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserWorkContracts> getUserWorkContracts() {
    return userWorkContracts;
  }

  public void setUserWorkContracts(List<UserWorkContracts> userWorkContracts) {
    this.userWorkContracts = userWorkContracts;
  }

  public UserBean userLeaveVacationProfiles(List<UserLeaveVacationProfiles> userLeaveVacationProfiles) {
    this.userLeaveVacationProfiles = userLeaveVacationProfiles;
    return this;
  }

  public UserBean addUserLeaveVacationProfilesItem(UserLeaveVacationProfiles userLeaveVacationProfilesItem) {
    this.userLeaveVacationProfiles.add(userLeaveVacationProfilesItem);
    return this;
  }

   /**
   * Get userLeaveVacationProfiles
   * @return userLeaveVacationProfiles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserLeaveVacationProfiles> getUserLeaveVacationProfiles() {
    return userLeaveVacationProfiles;
  }

  public void setUserLeaveVacationProfiles(List<UserLeaveVacationProfiles> userLeaveVacationProfiles) {
    this.userLeaveVacationProfiles = userLeaveVacationProfiles;
  }

  public UserBean userAddress(List<UserAddress> userAddress) {
    this.userAddress = userAddress;
    return this;
  }

  public UserBean addUserAddressItem(UserAddress userAddressItem) {
    this.userAddress.add(userAddressItem);
    return this;
  }

   /**
   * Get userAddress
   * @return userAddress
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserAddress> getUserAddress() {
    return userAddress;
  }

  public void setUserAddress(List<UserAddress> userAddress) {
    this.userAddress = userAddress;
  }

  public UserBean userPhones(List<UserPhones> userPhones) {
    this.userPhones = userPhones;
    return this;
  }

  public UserBean addUserPhonesItem(UserPhones userPhonesItem) {
    this.userPhones.add(userPhonesItem);
    return this;
  }

   /**
   * Get userPhones
   * @return userPhones
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserPhones> getUserPhones() {
    return userPhones;
  }

  public void setUserPhones(List<UserPhones> userPhones) {
    this.userPhones = userPhones;
  }

  public UserBean userChildren(List<UserChildren> userChildren) {
    this.userChildren = userChildren;
    return this;
  }

  public UserBean addUserChildrenItem(UserChildren userChildrenItem) {
    this.userChildren.add(userChildrenItem);
    return this;
  }

   /**
   * Get userChildren
   * @return userChildren
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserChildren> getUserChildren() {
    return userChildren;
  }

  public void setUserChildren(List<UserChildren> userChildren) {
    this.userChildren = userChildren;
  }

  public UserBean userCompanyOrganizations(List<UserCompanyOrganization> userCompanyOrganizations) {
    this.userCompanyOrganizations = userCompanyOrganizations;
    return this;
  }

  public UserBean addUserCompanyOrganizationsItem(UserCompanyOrganization userCompanyOrganizationsItem) {
    this.userCompanyOrganizations.add(userCompanyOrganizationsItem);
    return this;
  }

   /**
   * Get userCompanyOrganizations
   * @return userCompanyOrganizations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserCompanyOrganization> getUserCompanyOrganizations() {
    return userCompanyOrganizations;
  }

  public void setUserCompanyOrganizations(List<UserCompanyOrganization> userCompanyOrganizations) {
    this.userCompanyOrganizations = userCompanyOrganizations;
  }

  public UserBean userTokenDeviceConnections(List<UserTokenDeviceConnection> userTokenDeviceConnections) {
    this.userTokenDeviceConnections = userTokenDeviceConnections;
    return this;
  }

  public UserBean addUserTokenDeviceConnectionsItem(UserTokenDeviceConnection userTokenDeviceConnectionsItem) {
    this.userTokenDeviceConnections.add(userTokenDeviceConnectionsItem);
    return this;
  }

   /**
   * Get userTokenDeviceConnections
   * @return userTokenDeviceConnections
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserTokenDeviceConnection> getUserTokenDeviceConnections() {
    return userTokenDeviceConnections;
  }

  public void setUserTokenDeviceConnections(List<UserTokenDeviceConnection> userTokenDeviceConnections) {
    this.userTokenDeviceConnections = userTokenDeviceConnections;
  }

  public UserBean userWidgetsPref(List<UserWidgetsPref> userWidgetsPref) {
    this.userWidgetsPref = userWidgetsPref;
    return this;
  }

  public UserBean addUserWidgetsPrefItem(UserWidgetsPref userWidgetsPrefItem) {
    this.userWidgetsPref.add(userWidgetsPrefItem);
    return this;
  }

   /**
   * Get userWidgetsPref
   * @return userWidgetsPref
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserWidgetsPref> getUserWidgetsPref() {
    return userWidgetsPref;
  }

  public void setUserWidgetsPref(List<UserWidgetsPref> userWidgetsPref) {
    this.userWidgetsPref = userWidgetsPref;
  }

  public UserBean userWellBeingVotes(List<UserWellBeingVote> userWellBeingVotes) {
    this.userWellBeingVotes = userWellBeingVotes;
    return this;
  }

  public UserBean addUserWellBeingVotesItem(UserWellBeingVote userWellBeingVotesItem) {
    this.userWellBeingVotes.add(userWellBeingVotesItem);
    return this;
  }

   /**
   * Get userWellBeingVotes
   * @return userWellBeingVotes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserWellBeingVote> getUserWellBeingVotes() {
    return userWellBeingVotes;
  }

  public void setUserWellBeingVotes(List<UserWellBeingVote> userWellBeingVotes) {
    this.userWellBeingVotes = userWellBeingVotes;
  }

  public UserBean userProducts(List<UserProduct> userProducts) {
    this.userProducts = userProducts;
    return this;
  }

  public UserBean addUserProductsItem(UserProduct userProductsItem) {
    this.userProducts.add(userProductsItem);
    return this;
  }

   /**
   * Get userProducts
   * @return userProducts
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserProduct> getUserProducts() {
    return userProducts;
  }

  public void setUserProducts(List<UserProduct> userProducts) {
    this.userProducts = userProducts;
  }

  public UserBean userInformation(String userInformation) {
    this.userInformation = userInformation;
    return this;
  }

   /**
   * Get userInformation
   * @return userInformation
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserInformation() {
    return userInformation;
  }

  public void setUserInformation(String userInformation) {
    this.userInformation = userInformation;
  }

  public UserBean idCompany(String idCompany) {
    this.idCompany = idCompany;
    return this;
  }

   /**
   * Get idCompany
   * @return idCompany
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdCompany() {
    return idCompany;
  }

  public void setIdCompany(String idCompany) {
    this.idCompany = idCompany;
  }

  public UserBean idUser(String idUser) {
    this.idUser = idUser;
    return this;
  }

   /**
   * Get idUser
   * @return idUser
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdUser() {
    return idUser;
  }

  public void setIdUser(String idUser) {
    this.idUser = idUser;
  }

  public UserBean controllerInstance(GlobalControler controllerInstance) {
    this.controllerInstance = controllerInstance;
    return this;
  }

   /**
   * Get controllerInstance
   * @return controllerInstance
  **/
  @ApiModelProperty(example = "null", value = "")
  public GlobalControler getControllerInstance() {
    return controllerInstance;
  }

  public void setControllerInstance(GlobalControler controllerInstance) {
    this.controllerInstance = controllerInstance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserBean userBean = (UserBean) o;
    return Objects.equals(this.userCreate, userBean.userCreate) &&
        Objects.equals(this.dateCreate, userBean.dateCreate) &&
        Objects.equals(this.userUpdate, userBean.userUpdate) &&
        Objects.equals(this.dateUpdate, userBean.dateUpdate) &&
        Objects.equals(this.internalCode, userBean.internalCode) &&
        Objects.equals(this.id, userBean.id) &&
        Objects.equals(this.userGender, userBean.userGender) &&
        Objects.equals(this.userFirstName, userBean.userFirstName) &&
        Objects.equals(this.userLastName, userBean.userLastName) &&
        Objects.equals(this.userEmail, userBean.userEmail) &&
        Objects.equals(this.userEmailTempKey, userBean.userEmailTempKey) &&
        Objects.equals(this.userSerial, userBean.userSerial) &&
        Objects.equals(this.userPwd, userBean.userPwd) &&
        Objects.equals(this.userLocale, userBean.userLocale) &&
        Objects.equals(this.userProfileId, userBean.userProfileId) &&
        Objects.equals(this.userPhoto, userBean.userPhoto) &&
        Objects.equals(this.userFunction, userBean.userFunction) &&
        Objects.equals(this.userBirthDay, userBean.userBirthDay) &&
        Objects.equals(this.userMaritalStatus, userBean.userMaritalStatus) &&
        Objects.equals(this.isAnAdmin, userBean.isAnAdmin) &&
        Objects.equals(this.userPayroll, userBean.userPayroll) &&
        Objects.equals(this.userWorkCategory, userBean.userWorkCategory) &&
        Objects.equals(this.userWorkLevel, userBean.userWorkLevel) &&
        Objects.equals(this.userEchelon, userBean.userEchelon) &&
        Objects.equals(this.userTimeZone, userBean.userTimeZone) &&
        Objects.equals(this.appRole, userBean.appRole) &&
        Objects.equals(this.userHiringDate, userBean.userHiringDate) &&
        Objects.equals(this.userDepartureDate, userBean.userDepartureDate) &&
        Objects.equals(this.userDaysOffId, userBean.userDaysOffId) &&
        Objects.equals(this.hasAccessToAzuneedPortal, userBean.hasAccessToAzuneedPortal) &&
        Objects.equals(this.tco, userBean.tco) &&
        Objects.equals(this.linkedUserRelation, userBean.linkedUserRelation) &&
        Objects.equals(this.linkedManagerRelation, userBean.linkedManagerRelation) &&
        Objects.equals(this.userWorkedHours, userBean.userWorkedHours) &&
        Objects.equals(this.userWorkContracts, userBean.userWorkContracts) &&
        Objects.equals(this.userLeaveVacationProfiles, userBean.userLeaveVacationProfiles) &&
        Objects.equals(this.userAddress, userBean.userAddress) &&
        Objects.equals(this.userPhones, userBean.userPhones) &&
        Objects.equals(this.userChildren, userBean.userChildren) &&
        Objects.equals(this.userCompanyOrganizations, userBean.userCompanyOrganizations) &&
        Objects.equals(this.userTokenDeviceConnections, userBean.userTokenDeviceConnections) &&
        Objects.equals(this.userWidgetsPref, userBean.userWidgetsPref) &&
        Objects.equals(this.userWellBeingVotes, userBean.userWellBeingVotes) &&
        Objects.equals(this.userProducts, userBean.userProducts) &&
        Objects.equals(this.userInformation, userBean.userInformation) &&
        Objects.equals(this.idCompany, userBean.idCompany) &&
        Objects.equals(this.idUser, userBean.idUser) &&
        Objects.equals(this.controllerInstance, userBean.controllerInstance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userCreate, dateCreate, userUpdate, dateUpdate, internalCode, id, userGender, userFirstName, userLastName, userEmail, userEmailTempKey, userSerial, userPwd, userLocale, userProfileId, userPhoto, userFunction, userBirthDay, userMaritalStatus, isAnAdmin, userPayroll, userWorkCategory, userWorkLevel, userEchelon, userTimeZone, appRole, userHiringDate, userDepartureDate, userDaysOffId, hasAccessToAzuneedPortal, tco, linkedUserRelation, linkedManagerRelation, userWorkedHours, userWorkContracts, userLeaveVacationProfiles, userAddress, userPhones, userChildren, userCompanyOrganizations, userTokenDeviceConnections, userWidgetsPref, userWellBeingVotes, userProducts, userInformation, idCompany, idUser, controllerInstance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserBean {\n");
    
    sb.append("    userCreate: ").append(toIndentedString(userCreate)).append("\n");
    sb.append("    dateCreate: ").append(toIndentedString(dateCreate)).append("\n");
    sb.append("    userUpdate: ").append(toIndentedString(userUpdate)).append("\n");
    sb.append("    dateUpdate: ").append(toIndentedString(dateUpdate)).append("\n");
    sb.append("    internalCode: ").append(toIndentedString(internalCode)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userGender: ").append(toIndentedString(userGender)).append("\n");
    sb.append("    userFirstName: ").append(toIndentedString(userFirstName)).append("\n");
    sb.append("    userLastName: ").append(toIndentedString(userLastName)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    userEmailTempKey: ").append(toIndentedString(userEmailTempKey)).append("\n");
    sb.append("    userSerial: ").append(toIndentedString(userSerial)).append("\n");
    sb.append("    userPwd: ").append(toIndentedString(userPwd)).append("\n");
    sb.append("    userLocale: ").append(toIndentedString(userLocale)).append("\n");
    sb.append("    userProfileId: ").append(toIndentedString(userProfileId)).append("\n");
    sb.append("    userPhoto: ").append(toIndentedString(userPhoto)).append("\n");
    sb.append("    userFunction: ").append(toIndentedString(userFunction)).append("\n");
    sb.append("    userBirthDay: ").append(toIndentedString(userBirthDay)).append("\n");
    sb.append("    userMaritalStatus: ").append(toIndentedString(userMaritalStatus)).append("\n");
    sb.append("    isAnAdmin: ").append(toIndentedString(isAnAdmin)).append("\n");
    sb.append("    userPayroll: ").append(toIndentedString(userPayroll)).append("\n");
    sb.append("    userWorkCategory: ").append(toIndentedString(userWorkCategory)).append("\n");
    sb.append("    userWorkLevel: ").append(toIndentedString(userWorkLevel)).append("\n");
    sb.append("    userEchelon: ").append(toIndentedString(userEchelon)).append("\n");
    sb.append("    userTimeZone: ").append(toIndentedString(userTimeZone)).append("\n");
    sb.append("    appRole: ").append(toIndentedString(appRole)).append("\n");
    sb.append("    userHiringDate: ").append(toIndentedString(userHiringDate)).append("\n");
    sb.append("    userDepartureDate: ").append(toIndentedString(userDepartureDate)).append("\n");
    sb.append("    userDaysOffId: ").append(toIndentedString(userDaysOffId)).append("\n");
    sb.append("    hasAccessToAzuneedPortal: ").append(toIndentedString(hasAccessToAzuneedPortal)).append("\n");
    sb.append("    tco: ").append(toIndentedString(tco)).append("\n");
    sb.append("    linkedUserRelation: ").append(toIndentedString(linkedUserRelation)).append("\n");
    sb.append("    linkedManagerRelation: ").append(toIndentedString(linkedManagerRelation)).append("\n");
    sb.append("    userWorkedHours: ").append(toIndentedString(userWorkedHours)).append("\n");
    sb.append("    userWorkContracts: ").append(toIndentedString(userWorkContracts)).append("\n");
    sb.append("    userLeaveVacationProfiles: ").append(toIndentedString(userLeaveVacationProfiles)).append("\n");
    sb.append("    userAddress: ").append(toIndentedString(userAddress)).append("\n");
    sb.append("    userPhones: ").append(toIndentedString(userPhones)).append("\n");
    sb.append("    userChildren: ").append(toIndentedString(userChildren)).append("\n");
    sb.append("    userCompanyOrganizations: ").append(toIndentedString(userCompanyOrganizations)).append("\n");
    sb.append("    userTokenDeviceConnections: ").append(toIndentedString(userTokenDeviceConnections)).append("\n");
    sb.append("    userWidgetsPref: ").append(toIndentedString(userWidgetsPref)).append("\n");
    sb.append("    userWellBeingVotes: ").append(toIndentedString(userWellBeingVotes)).append("\n");
    sb.append("    userProducts: ").append(toIndentedString(userProducts)).append("\n");
    sb.append("    userInformation: ").append(toIndentedString(userInformation)).append("\n");
    sb.append("    idCompany: ").append(toIndentedString(idCompany)).append("\n");
    sb.append("    idUser: ").append(toIndentedString(idUser)).append("\n");
    sb.append("    controllerInstance: ").append(toIndentedString(controllerInstance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

