/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UserPhonesId;


/**
 * UserPhones
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:24:13.221+01:00")
public class UserPhones   {
  @SerializedName("linkedUserRelation")
  private String linkedUserRelation = null;

  @SerializedName("id")
  private UserPhonesId id = null;

  @SerializedName("phonesType")
  private String phonesType = null;

  @SerializedName("phonesPrefixCode")
  private String phonesPrefixCode = null;

  @SerializedName("phonesNumber")
  private String phonesNumber = null;

  @SerializedName("phonesComment")
  private String phonesComment = null;

  public UserPhones linkedUserRelation(String linkedUserRelation) {
    this.linkedUserRelation = linkedUserRelation;
    return this;
  }

   /**
   * Get linkedUserRelation
   * @return linkedUserRelation
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLinkedUserRelation() {
    return linkedUserRelation;
  }

  public void setLinkedUserRelation(String linkedUserRelation) {
    this.linkedUserRelation = linkedUserRelation;
  }

  public UserPhones id(UserPhonesId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserPhonesId getId() {
    return id;
  }

  public void setId(UserPhonesId id) {
    this.id = id;
  }

  public UserPhones phonesType(String phonesType) {
    this.phonesType = phonesType;
    return this;
  }

   /**
   * Get phonesType
   * @return phonesType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhonesType() {
    return phonesType;
  }

  public void setPhonesType(String phonesType) {
    this.phonesType = phonesType;
  }

  public UserPhones phonesPrefixCode(String phonesPrefixCode) {
    this.phonesPrefixCode = phonesPrefixCode;
    return this;
  }

   /**
   * Get phonesPrefixCode
   * @return phonesPrefixCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhonesPrefixCode() {
    return phonesPrefixCode;
  }

  public void setPhonesPrefixCode(String phonesPrefixCode) {
    this.phonesPrefixCode = phonesPrefixCode;
  }

  public UserPhones phonesNumber(String phonesNumber) {
    this.phonesNumber = phonesNumber;
    return this;
  }

   /**
   * Get phonesNumber
   * @return phonesNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhonesNumber() {
    return phonesNumber;
  }

  public void setPhonesNumber(String phonesNumber) {
    this.phonesNumber = phonesNumber;
  }

  public UserPhones phonesComment(String phonesComment) {
    this.phonesComment = phonesComment;
    return this;
  }

   /**
   * Get phonesComment
   * @return phonesComment
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhonesComment() {
    return phonesComment;
  }

  public void setPhonesComment(String phonesComment) {
    this.phonesComment = phonesComment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserPhones userPhones = (UserPhones) o;
    return Objects.equals(this.linkedUserRelation, userPhones.linkedUserRelation) &&
        Objects.equals(this.id, userPhones.id) &&
        Objects.equals(this.phonesType, userPhones.phonesType) &&
        Objects.equals(this.phonesPrefixCode, userPhones.phonesPrefixCode) &&
        Objects.equals(this.phonesNumber, userPhones.phonesNumber) &&
        Objects.equals(this.phonesComment, userPhones.phonesComment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkedUserRelation, id, phonesType, phonesPrefixCode, phonesNumber, phonesComment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPhones {\n");
    
    sb.append("    linkedUserRelation: ").append(toIndentedString(linkedUserRelation)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    phonesType: ").append(toIndentedString(phonesType)).append("\n");
    sb.append("    phonesPrefixCode: ").append(toIndentedString(phonesPrefixCode)).append("\n");
    sb.append("    phonesNumber: ").append(toIndentedString(phonesNumber)).append("\n");
    sb.append("    phonesComment: ").append(toIndentedString(phonesComment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

