/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.GlobalControler;
import org.joda.time.DateTime;


/**
 * UserTokenDeviceConnection
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:24:13.221+01:00")
public class UserTokenDeviceConnection   {
  @SerializedName("userCreate")
  private String userCreate = null;

  @SerializedName("dateCreate")
  private DateTime dateCreate = null;

  @SerializedName("userUpdate")
  private String userUpdate = null;

  @SerializedName("dateUpdate")
  private DateTime dateUpdate = null;

  @SerializedName("internalCode")
  private String internalCode = null;

  @SerializedName("id")
  private Object id = null;

  @SerializedName("creationDate")
  private DateTime creationDate = null;

  @SerializedName("device")
  private String device = null;

  @SerializedName("idCompany")
  private String idCompany = null;

  @SerializedName("idUser")
  private String idUser = null;

  @SerializedName("controllerInstance")
  private GlobalControler controllerInstance = null;

  public UserTokenDeviceConnection userCreate(String userCreate) {
    this.userCreate = userCreate;
    return this;
  }

   /**
   * Get userCreate
   * @return userCreate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserCreate() {
    return userCreate;
  }

  public void setUserCreate(String userCreate) {
    this.userCreate = userCreate;
  }

  public UserTokenDeviceConnection dateCreate(DateTime dateCreate) {
    this.dateCreate = dateCreate;
    return this;
  }

   /**
   * Get dateCreate
   * @return dateCreate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateCreate() {
    return dateCreate;
  }

  public void setDateCreate(DateTime dateCreate) {
    this.dateCreate = dateCreate;
  }

  public UserTokenDeviceConnection userUpdate(String userUpdate) {
    this.userUpdate = userUpdate;
    return this;
  }

   /**
   * Get userUpdate
   * @return userUpdate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserUpdate() {
    return userUpdate;
  }

  public void setUserUpdate(String userUpdate) {
    this.userUpdate = userUpdate;
  }

  public UserTokenDeviceConnection dateUpdate(DateTime dateUpdate) {
    this.dateUpdate = dateUpdate;
    return this;
  }

   /**
   * Get dateUpdate
   * @return dateUpdate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateUpdate() {
    return dateUpdate;
  }

  public void setDateUpdate(DateTime dateUpdate) {
    this.dateUpdate = dateUpdate;
  }

  public UserTokenDeviceConnection internalCode(String internalCode) {
    this.internalCode = internalCode;
    return this;
  }

   /**
   * Get internalCode
   * @return internalCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInternalCode() {
    return internalCode;
  }

  public void setInternalCode(String internalCode) {
    this.internalCode = internalCode;
  }

  public UserTokenDeviceConnection id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public UserTokenDeviceConnection creationDate(DateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(DateTime creationDate) {
    this.creationDate = creationDate;
  }

  public UserTokenDeviceConnection device(String device) {
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDevice() {
    return device;
  }

  public void setDevice(String device) {
    this.device = device;
  }

  public UserTokenDeviceConnection idCompany(String idCompany) {
    this.idCompany = idCompany;
    return this;
  }

   /**
   * Get idCompany
   * @return idCompany
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdCompany() {
    return idCompany;
  }

  public void setIdCompany(String idCompany) {
    this.idCompany = idCompany;
  }

  public UserTokenDeviceConnection idUser(String idUser) {
    this.idUser = idUser;
    return this;
  }

   /**
   * Get idUser
   * @return idUser
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIdUser() {
    return idUser;
  }

  public void setIdUser(String idUser) {
    this.idUser = idUser;
  }

  public UserTokenDeviceConnection controllerInstance(GlobalControler controllerInstance) {
    this.controllerInstance = controllerInstance;
    return this;
  }

   /**
   * Get controllerInstance
   * @return controllerInstance
  **/
  @ApiModelProperty(example = "null", value = "")
  public GlobalControler getControllerInstance() {
    return controllerInstance;
  }

  public void setControllerInstance(GlobalControler controllerInstance) {
    this.controllerInstance = controllerInstance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserTokenDeviceConnection userTokenDeviceConnection = (UserTokenDeviceConnection) o;
    return Objects.equals(this.userCreate, userTokenDeviceConnection.userCreate) &&
        Objects.equals(this.dateCreate, userTokenDeviceConnection.dateCreate) &&
        Objects.equals(this.userUpdate, userTokenDeviceConnection.userUpdate) &&
        Objects.equals(this.dateUpdate, userTokenDeviceConnection.dateUpdate) &&
        Objects.equals(this.internalCode, userTokenDeviceConnection.internalCode) &&
        Objects.equals(this.id, userTokenDeviceConnection.id) &&
        Objects.equals(this.creationDate, userTokenDeviceConnection.creationDate) &&
        Objects.equals(this.device, userTokenDeviceConnection.device) &&
        Objects.equals(this.idCompany, userTokenDeviceConnection.idCompany) &&
        Objects.equals(this.idUser, userTokenDeviceConnection.idUser) &&
        Objects.equals(this.controllerInstance, userTokenDeviceConnection.controllerInstance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userCreate, dateCreate, userUpdate, dateUpdate, internalCode, id, creationDate, device, idCompany, idUser, controllerInstance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserTokenDeviceConnection {\n");
    
    sb.append("    userCreate: ").append(toIndentedString(userCreate)).append("\n");
    sb.append("    dateCreate: ").append(toIndentedString(dateCreate)).append("\n");
    sb.append("    userUpdate: ").append(toIndentedString(userUpdate)).append("\n");
    sb.append("    dateUpdate: ").append(toIndentedString(dateUpdate)).append("\n");
    sb.append("    internalCode: ").append(toIndentedString(internalCode)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    idCompany: ").append(toIndentedString(idCompany)).append("\n");
    sb.append("    idUser: ").append(toIndentedString(idUser)).append("\n");
    sb.append("    controllerInstance: ").append(toIndentedString(controllerInstance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

