/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UserProductId;


/**
 * UserProductItem
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T16:24:13.221+01:00")
public class UserProductItem   {
  @SerializedName("id")
  private UserProductId id = null;

  @SerializedName("productLabel")
  private String productLabel = null;

  @SerializedName("crmProductId")
  private String crmProductId = null;

  public UserProductItem id(UserProductId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserProductId getId() {
    return id;
  }

  public void setId(UserProductId id) {
    this.id = id;
  }

  public UserProductItem productLabel(String productLabel) {
    this.productLabel = productLabel;
    return this;
  }

   /**
   * Get productLabel
   * @return productLabel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProductLabel() {
    return productLabel;
  }

  public void setProductLabel(String productLabel) {
    this.productLabel = productLabel;
  }

  public UserProductItem crmProductId(String crmProductId) {
    this.crmProductId = crmProductId;
    return this;
  }

   /**
   * Get crmProductId
   * @return crmProductId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCrmProductId() {
    return crmProductId;
  }

  public void setCrmProductId(String crmProductId) {
    this.crmProductId = crmProductId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserProductItem userProductItem = (UserProductItem) o;
    return Objects.equals(this.id, userProductItem.id) &&
        Objects.equals(this.productLabel, userProductItem.productLabel) &&
        Objects.equals(this.crmProductId, userProductItem.crmProductId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, productLabel, crmProductId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserProductItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    productLabel: ").append(toIndentedString(productLabel)).append("\n");
    sb.append("    crmProductId: ").append(toIndentedString(crmProductId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

